// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenet_block_accel_pw_row_stage_Pipeline_PW_LOAD_IN (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        c_in,
        input_buf_15_address0,
        input_buf_15_ce0,
        input_buf_15_we0,
        input_buf_15_d0,
        input_buf_14_address0,
        input_buf_14_ce0,
        input_buf_14_we0,
        input_buf_14_d0,
        input_buf_13_address0,
        input_buf_13_ce0,
        input_buf_13_we0,
        input_buf_13_d0,
        input_buf_12_address0,
        input_buf_12_ce0,
        input_buf_12_we0,
        input_buf_12_d0,
        input_buf_11_address0,
        input_buf_11_ce0,
        input_buf_11_we0,
        input_buf_11_d0,
        input_buf_10_address0,
        input_buf_10_ce0,
        input_buf_10_we0,
        input_buf_10_d0,
        input_buf_9_address0,
        input_buf_9_ce0,
        input_buf_9_we0,
        input_buf_9_d0,
        input_buf_8_address0,
        input_buf_8_ce0,
        input_buf_8_we0,
        input_buf_8_d0,
        input_buf_7_address0,
        input_buf_7_ce0,
        input_buf_7_we0,
        input_buf_7_d0,
        input_buf_6_address0,
        input_buf_6_ce0,
        input_buf_6_we0,
        input_buf_6_d0,
        input_buf_5_address0,
        input_buf_5_ce0,
        input_buf_5_we0,
        input_buf_5_d0,
        input_buf_4_address0,
        input_buf_4_ce0,
        input_buf_4_we0,
        input_buf_4_d0,
        input_buf_3_address0,
        input_buf_3_ce0,
        input_buf_3_we0,
        input_buf_3_d0,
        input_buf_2_address0,
        input_buf_2_ce0,
        input_buf_2_we0,
        input_buf_2_d0,
        input_buf_1_address0,
        input_buf_1_ce0,
        input_buf_1_we0,
        input_buf_1_d0,
        input_buf_address0,
        input_buf_ce0,
        input_buf_we0,
        input_buf_d0,
        mul_ln368,
        inter_buf_0_address0,
        inter_buf_0_ce0,
        inter_buf_0_q0,
        inter_buf_1_address0,
        inter_buf_1_ce0,
        inter_buf_1_q0,
        inter_buf_2_address0,
        inter_buf_2_ce0,
        inter_buf_2_q0,
        inter_buf_3_address0,
        inter_buf_3_ce0,
        inter_buf_3_q0,
        inter_buf_4_address0,
        inter_buf_4_ce0,
        inter_buf_4_q0,
        inter_buf_5_address0,
        inter_buf_5_ce0,
        inter_buf_5_q0,
        inter_buf_6_address0,
        inter_buf_6_ce0,
        inter_buf_6_q0,
        inter_buf_7_address0,
        inter_buf_7_ce0,
        inter_buf_7_q0,
        inter_buf_8_address0,
        inter_buf_8_ce0,
        inter_buf_8_q0,
        inter_buf_9_address0,
        inter_buf_9_ce0,
        inter_buf_9_q0,
        inter_buf_10_address0,
        inter_buf_10_ce0,
        inter_buf_10_q0,
        inter_buf_11_address0,
        inter_buf_11_ce0,
        inter_buf_11_q0,
        inter_buf_12_address0,
        inter_buf_12_ce0,
        inter_buf_12_q0,
        inter_buf_13_address0,
        inter_buf_13_ce0,
        inter_buf_13_q0,
        inter_buf_14_address0,
        inter_buf_14_ce0,
        inter_buf_14_q0,
        inter_buf_15_address0,
        inter_buf_15_ce0,
        inter_buf_15_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] c_in;
output  [5:0] input_buf_15_address0;
output   input_buf_15_ce0;
output   input_buf_15_we0;
output  [7:0] input_buf_15_d0;
output  [5:0] input_buf_14_address0;
output   input_buf_14_ce0;
output   input_buf_14_we0;
output  [7:0] input_buf_14_d0;
output  [5:0] input_buf_13_address0;
output   input_buf_13_ce0;
output   input_buf_13_we0;
output  [7:0] input_buf_13_d0;
output  [5:0] input_buf_12_address0;
output   input_buf_12_ce0;
output   input_buf_12_we0;
output  [7:0] input_buf_12_d0;
output  [5:0] input_buf_11_address0;
output   input_buf_11_ce0;
output   input_buf_11_we0;
output  [7:0] input_buf_11_d0;
output  [5:0] input_buf_10_address0;
output   input_buf_10_ce0;
output   input_buf_10_we0;
output  [7:0] input_buf_10_d0;
output  [5:0] input_buf_9_address0;
output   input_buf_9_ce0;
output   input_buf_9_we0;
output  [7:0] input_buf_9_d0;
output  [5:0] input_buf_8_address0;
output   input_buf_8_ce0;
output   input_buf_8_we0;
output  [7:0] input_buf_8_d0;
output  [5:0] input_buf_7_address0;
output   input_buf_7_ce0;
output   input_buf_7_we0;
output  [7:0] input_buf_7_d0;
output  [5:0] input_buf_6_address0;
output   input_buf_6_ce0;
output   input_buf_6_we0;
output  [7:0] input_buf_6_d0;
output  [5:0] input_buf_5_address0;
output   input_buf_5_ce0;
output   input_buf_5_we0;
output  [7:0] input_buf_5_d0;
output  [5:0] input_buf_4_address0;
output   input_buf_4_ce0;
output   input_buf_4_we0;
output  [7:0] input_buf_4_d0;
output  [5:0] input_buf_3_address0;
output   input_buf_3_ce0;
output   input_buf_3_we0;
output  [7:0] input_buf_3_d0;
output  [5:0] input_buf_2_address0;
output   input_buf_2_ce0;
output   input_buf_2_we0;
output  [7:0] input_buf_2_d0;
output  [5:0] input_buf_1_address0;
output   input_buf_1_ce0;
output   input_buf_1_we0;
output  [7:0] input_buf_1_d0;
output  [5:0] input_buf_address0;
output   input_buf_ce0;
output   input_buf_we0;
output  [7:0] input_buf_d0;
input  [16:0] mul_ln368;
output  [12:0] inter_buf_0_address0;
output   inter_buf_0_ce0;
input  [7:0] inter_buf_0_q0;
output  [12:0] inter_buf_1_address0;
output   inter_buf_1_ce0;
input  [7:0] inter_buf_1_q0;
output  [12:0] inter_buf_2_address0;
output   inter_buf_2_ce0;
input  [7:0] inter_buf_2_q0;
output  [12:0] inter_buf_3_address0;
output   inter_buf_3_ce0;
input  [7:0] inter_buf_3_q0;
output  [12:0] inter_buf_4_address0;
output   inter_buf_4_ce0;
input  [7:0] inter_buf_4_q0;
output  [12:0] inter_buf_5_address0;
output   inter_buf_5_ce0;
input  [7:0] inter_buf_5_q0;
output  [12:0] inter_buf_6_address0;
output   inter_buf_6_ce0;
input  [7:0] inter_buf_6_q0;
output  [12:0] inter_buf_7_address0;
output   inter_buf_7_ce0;
input  [7:0] inter_buf_7_q0;
output  [12:0] inter_buf_8_address0;
output   inter_buf_8_ce0;
input  [7:0] inter_buf_8_q0;
output  [12:0] inter_buf_9_address0;
output   inter_buf_9_ce0;
input  [7:0] inter_buf_9_q0;
output  [12:0] inter_buf_10_address0;
output   inter_buf_10_ce0;
input  [7:0] inter_buf_10_q0;
output  [12:0] inter_buf_11_address0;
output   inter_buf_11_ce0;
input  [7:0] inter_buf_11_q0;
output  [12:0] inter_buf_12_address0;
output   inter_buf_12_ce0;
input  [7:0] inter_buf_12_q0;
output  [12:0] inter_buf_13_address0;
output   inter_buf_13_ce0;
input  [7:0] inter_buf_13_q0;
output  [12:0] inter_buf_14_address0;
output   inter_buf_14_ce0;
input  [7:0] inter_buf_14_q0;
output  [12:0] inter_buf_15_address0;
output   inter_buf_15_ce0;
input  [7:0] inter_buf_15_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln370_fu_580_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] trunc_ln370_1_fu_596_p1;
reg   [3:0] trunc_ln370_1_reg_771;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] lshr_ln_reg_775;
wire   [3:0] trunc_ln372_fu_616_p1;
reg   [3:0] trunc_ln372_reg_780;
wire   [63:0] zext_ln372_fu_630_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln370_1_fu_655_p1;
reg   [30:0] ci_fu_136;
wire   [30:0] add_ln370_fu_586_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_ci_2;
reg    inter_buf_0_ce0_local;
reg    inter_buf_1_ce0_local;
reg    inter_buf_2_ce0_local;
reg    inter_buf_3_ce0_local;
reg    inter_buf_4_ce0_local;
reg    inter_buf_5_ce0_local;
reg    inter_buf_6_ce0_local;
reg    inter_buf_7_ce0_local;
reg    inter_buf_8_ce0_local;
reg    inter_buf_9_ce0_local;
reg    inter_buf_10_ce0_local;
reg    inter_buf_11_ce0_local;
reg    inter_buf_12_ce0_local;
reg    inter_buf_13_ce0_local;
reg    inter_buf_14_ce0_local;
reg    inter_buf_15_ce0_local;
reg    input_buf_14_we0_local;
wire   [7:0] tmp_1_fu_674_p35;
reg    input_buf_14_ce0_local;
reg    input_buf_13_we0_local;
reg    input_buf_13_ce0_local;
reg    input_buf_12_we0_local;
reg    input_buf_12_ce0_local;
reg    input_buf_11_we0_local;
reg    input_buf_11_ce0_local;
reg    input_buf_10_we0_local;
reg    input_buf_10_ce0_local;
reg    input_buf_9_we0_local;
reg    input_buf_9_ce0_local;
reg    input_buf_8_we0_local;
reg    input_buf_8_ce0_local;
reg    input_buf_7_we0_local;
reg    input_buf_7_ce0_local;
reg    input_buf_6_we0_local;
reg    input_buf_6_ce0_local;
reg    input_buf_5_we0_local;
reg    input_buf_5_ce0_local;
reg    input_buf_4_we0_local;
reg    input_buf_4_ce0_local;
reg    input_buf_3_we0_local;
reg    input_buf_3_ce0_local;
reg    input_buf_2_we0_local;
reg    input_buf_2_ce0_local;
reg    input_buf_1_we0_local;
reg    input_buf_1_ce0_local;
reg    input_buf_we0_local;
reg    input_buf_ce0_local;
reg    input_buf_15_we0_local;
reg    input_buf_15_ce0_local;
wire   [31:0] zext_ln370_fu_576_p1;
wire   [16:0] trunc_ln370_fu_592_p1;
wire   [16:0] add_ln372_fu_610_p2;
wire   [12:0] lshr_ln1_fu_620_p4;
wire   [7:0] tmp_1_fu_674_p33;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] tmp_1_fu_674_p1;
wire   [3:0] tmp_1_fu_674_p3;
wire   [3:0] tmp_1_fu_674_p5;
wire   [3:0] tmp_1_fu_674_p7;
wire   [3:0] tmp_1_fu_674_p9;
wire   [3:0] tmp_1_fu_674_p11;
wire   [3:0] tmp_1_fu_674_p13;
wire   [3:0] tmp_1_fu_674_p15;
wire  signed [3:0] tmp_1_fu_674_p17;
wire  signed [3:0] tmp_1_fu_674_p19;
wire  signed [3:0] tmp_1_fu_674_p21;
wire  signed [3:0] tmp_1_fu_674_p23;
wire  signed [3:0] tmp_1_fu_674_p25;
wire  signed [3:0] tmp_1_fu_674_p27;
wire  signed [3:0] tmp_1_fu_674_p29;
wire  signed [3:0] tmp_1_fu_674_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ci_fu_136 = 31'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) mobilenet_block_accel_sparsemux_33_4_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 8 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 8 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 8 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 8 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 8 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 8 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 8 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 8 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
sparsemux_33_4_8_1_1_U201(
    .din0(inter_buf_0_q0),
    .din1(inter_buf_1_q0),
    .din2(inter_buf_2_q0),
    .din3(inter_buf_3_q0),
    .din4(inter_buf_4_q0),
    .din5(inter_buf_5_q0),
    .din6(inter_buf_6_q0),
    .din7(inter_buf_7_q0),
    .din8(inter_buf_8_q0),
    .din9(inter_buf_9_q0),
    .din10(inter_buf_10_q0),
    .din11(inter_buf_11_q0),
    .din12(inter_buf_12_q0),
    .din13(inter_buf_13_q0),
    .din14(inter_buf_14_q0),
    .din15(inter_buf_15_q0),
    .def(tmp_1_fu_674_p33),
    .sel(trunc_ln372_reg_780),
    .dout(tmp_1_fu_674_p35)
);

mobilenet_block_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln370_fu_580_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ci_fu_136 <= add_ln370_fu_586_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ci_fu_136 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln_reg_775 <= {{ap_sig_allocacmp_ci_2[9:4]}};
        trunc_ln370_1_reg_771 <= trunc_ln370_1_fu_596_p1;
        trunc_ln372_reg_780 <= trunc_ln372_fu_616_p1;
    end
end

always @ (*) begin
    if (((icmp_ln370_fu_580_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ci_2 = 31'd0;
    end else begin
        ap_sig_allocacmp_ci_2 = ci_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_10_ce0_local = 1'b1;
    end else begin
        input_buf_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_10_we0_local = 1'b1;
    end else begin
        input_buf_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_11_ce0_local = 1'b1;
    end else begin
        input_buf_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd11) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_11_we0_local = 1'b1;
    end else begin
        input_buf_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_12_ce0_local = 1'b1;
    end else begin
        input_buf_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_12_we0_local = 1'b1;
    end else begin
        input_buf_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_13_ce0_local = 1'b1;
    end else begin
        input_buf_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd13) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_13_we0_local = 1'b1;
    end else begin
        input_buf_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_14_ce0_local = 1'b1;
    end else begin
        input_buf_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd14) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_14_we0_local = 1'b1;
    end else begin
        input_buf_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_15_ce0_local = 1'b1;
    end else begin
        input_buf_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_15_we0_local = 1'b1;
    end else begin
        input_buf_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_1_ce0_local = 1'b1;
    end else begin
        input_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_1_we0_local = 1'b1;
    end else begin
        input_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_2_ce0_local = 1'b1;
    end else begin
        input_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_2_we0_local = 1'b1;
    end else begin
        input_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_3_ce0_local = 1'b1;
    end else begin
        input_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_3_we0_local = 1'b1;
    end else begin
        input_buf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_4_ce0_local = 1'b1;
    end else begin
        input_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_4_we0_local = 1'b1;
    end else begin
        input_buf_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_5_ce0_local = 1'b1;
    end else begin
        input_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_5_we0_local = 1'b1;
    end else begin
        input_buf_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_6_ce0_local = 1'b1;
    end else begin
        input_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_6_we0_local = 1'b1;
    end else begin
        input_buf_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_7_ce0_local = 1'b1;
    end else begin
        input_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_7_we0_local = 1'b1;
    end else begin
        input_buf_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_8_ce0_local = 1'b1;
    end else begin
        input_buf_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_8_we0_local = 1'b1;
    end else begin
        input_buf_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_9_ce0_local = 1'b1;
    end else begin
        input_buf_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd9) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_9_we0_local = 1'b1;
    end else begin
        input_buf_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_ce0_local = 1'b1;
    end else begin
        input_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln370_1_reg_771 == 4'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_buf_we0_local = 1'b1;
    end else begin
        input_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_0_ce0_local = 1'b1;
    end else begin
        inter_buf_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_10_ce0_local = 1'b1;
    end else begin
        inter_buf_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_11_ce0_local = 1'b1;
    end else begin
        inter_buf_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_12_ce0_local = 1'b1;
    end else begin
        inter_buf_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_13_ce0_local = 1'b1;
    end else begin
        inter_buf_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_14_ce0_local = 1'b1;
    end else begin
        inter_buf_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_15_ce0_local = 1'b1;
    end else begin
        inter_buf_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_1_ce0_local = 1'b1;
    end else begin
        inter_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_2_ce0_local = 1'b1;
    end else begin
        inter_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_3_ce0_local = 1'b1;
    end else begin
        inter_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_4_ce0_local = 1'b1;
    end else begin
        inter_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_5_ce0_local = 1'b1;
    end else begin
        inter_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_6_ce0_local = 1'b1;
    end else begin
        inter_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_7_ce0_local = 1'b1;
    end else begin
        inter_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_8_ce0_local = 1'b1;
    end else begin
        inter_buf_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inter_buf_9_ce0_local = 1'b1;
    end else begin
        inter_buf_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln370_fu_586_p2 = (ap_sig_allocacmp_ci_2 + 31'd1);

assign add_ln372_fu_610_p2 = (trunc_ln370_fu_592_p1 + mul_ln368);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln370_fu_580_p2 = (($signed(zext_ln370_fu_576_p1) < $signed(c_in)) ? 1'b1 : 1'b0);

assign input_buf_10_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_10_ce0 = input_buf_10_ce0_local;

assign input_buf_10_d0 = tmp_1_fu_674_p35;

assign input_buf_10_we0 = input_buf_10_we0_local;

assign input_buf_11_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_11_ce0 = input_buf_11_ce0_local;

assign input_buf_11_d0 = tmp_1_fu_674_p35;

assign input_buf_11_we0 = input_buf_11_we0_local;

assign input_buf_12_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_12_ce0 = input_buf_12_ce0_local;

assign input_buf_12_d0 = tmp_1_fu_674_p35;

assign input_buf_12_we0 = input_buf_12_we0_local;

assign input_buf_13_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_13_ce0 = input_buf_13_ce0_local;

assign input_buf_13_d0 = tmp_1_fu_674_p35;

assign input_buf_13_we0 = input_buf_13_we0_local;

assign input_buf_14_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_14_ce0 = input_buf_14_ce0_local;

assign input_buf_14_d0 = tmp_1_fu_674_p35;

assign input_buf_14_we0 = input_buf_14_we0_local;

assign input_buf_15_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_15_ce0 = input_buf_15_ce0_local;

assign input_buf_15_d0 = tmp_1_fu_674_p35;

assign input_buf_15_we0 = input_buf_15_we0_local;

assign input_buf_1_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_1_ce0 = input_buf_1_ce0_local;

assign input_buf_1_d0 = tmp_1_fu_674_p35;

assign input_buf_1_we0 = input_buf_1_we0_local;

assign input_buf_2_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_2_ce0 = input_buf_2_ce0_local;

assign input_buf_2_d0 = tmp_1_fu_674_p35;

assign input_buf_2_we0 = input_buf_2_we0_local;

assign input_buf_3_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_3_ce0 = input_buf_3_ce0_local;

assign input_buf_3_d0 = tmp_1_fu_674_p35;

assign input_buf_3_we0 = input_buf_3_we0_local;

assign input_buf_4_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_4_ce0 = input_buf_4_ce0_local;

assign input_buf_4_d0 = tmp_1_fu_674_p35;

assign input_buf_4_we0 = input_buf_4_we0_local;

assign input_buf_5_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_5_ce0 = input_buf_5_ce0_local;

assign input_buf_5_d0 = tmp_1_fu_674_p35;

assign input_buf_5_we0 = input_buf_5_we0_local;

assign input_buf_6_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_6_ce0 = input_buf_6_ce0_local;

assign input_buf_6_d0 = tmp_1_fu_674_p35;

assign input_buf_6_we0 = input_buf_6_we0_local;

assign input_buf_7_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_7_ce0 = input_buf_7_ce0_local;

assign input_buf_7_d0 = tmp_1_fu_674_p35;

assign input_buf_7_we0 = input_buf_7_we0_local;

assign input_buf_8_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_8_ce0 = input_buf_8_ce0_local;

assign input_buf_8_d0 = tmp_1_fu_674_p35;

assign input_buf_8_we0 = input_buf_8_we0_local;

assign input_buf_9_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_9_ce0 = input_buf_9_ce0_local;

assign input_buf_9_d0 = tmp_1_fu_674_p35;

assign input_buf_9_we0 = input_buf_9_we0_local;

assign input_buf_address0 = zext_ln370_1_fu_655_p1;

assign input_buf_ce0 = input_buf_ce0_local;

assign input_buf_d0 = tmp_1_fu_674_p35;

assign input_buf_we0 = input_buf_we0_local;

assign inter_buf_0_address0 = zext_ln372_fu_630_p1;

assign inter_buf_0_ce0 = inter_buf_0_ce0_local;

assign inter_buf_10_address0 = zext_ln372_fu_630_p1;

assign inter_buf_10_ce0 = inter_buf_10_ce0_local;

assign inter_buf_11_address0 = zext_ln372_fu_630_p1;

assign inter_buf_11_ce0 = inter_buf_11_ce0_local;

assign inter_buf_12_address0 = zext_ln372_fu_630_p1;

assign inter_buf_12_ce0 = inter_buf_12_ce0_local;

assign inter_buf_13_address0 = zext_ln372_fu_630_p1;

assign inter_buf_13_ce0 = inter_buf_13_ce0_local;

assign inter_buf_14_address0 = zext_ln372_fu_630_p1;

assign inter_buf_14_ce0 = inter_buf_14_ce0_local;

assign inter_buf_15_address0 = zext_ln372_fu_630_p1;

assign inter_buf_15_ce0 = inter_buf_15_ce0_local;

assign inter_buf_1_address0 = zext_ln372_fu_630_p1;

assign inter_buf_1_ce0 = inter_buf_1_ce0_local;

assign inter_buf_2_address0 = zext_ln372_fu_630_p1;

assign inter_buf_2_ce0 = inter_buf_2_ce0_local;

assign inter_buf_3_address0 = zext_ln372_fu_630_p1;

assign inter_buf_3_ce0 = inter_buf_3_ce0_local;

assign inter_buf_4_address0 = zext_ln372_fu_630_p1;

assign inter_buf_4_ce0 = inter_buf_4_ce0_local;

assign inter_buf_5_address0 = zext_ln372_fu_630_p1;

assign inter_buf_5_ce0 = inter_buf_5_ce0_local;

assign inter_buf_6_address0 = zext_ln372_fu_630_p1;

assign inter_buf_6_ce0 = inter_buf_6_ce0_local;

assign inter_buf_7_address0 = zext_ln372_fu_630_p1;

assign inter_buf_7_ce0 = inter_buf_7_ce0_local;

assign inter_buf_8_address0 = zext_ln372_fu_630_p1;

assign inter_buf_8_ce0 = inter_buf_8_ce0_local;

assign inter_buf_9_address0 = zext_ln372_fu_630_p1;

assign inter_buf_9_ce0 = inter_buf_9_ce0_local;

assign lshr_ln1_fu_620_p4 = {{add_ln372_fu_610_p2[16:4]}};

assign tmp_1_fu_674_p33 = 'bx;

assign trunc_ln370_1_fu_596_p1 = ap_sig_allocacmp_ci_2[3:0];

assign trunc_ln370_fu_592_p1 = ap_sig_allocacmp_ci_2[16:0];

assign trunc_ln372_fu_616_p1 = add_ln372_fu_610_p2[3:0];

assign zext_ln370_1_fu_655_p1 = lshr_ln_reg_775;

assign zext_ln370_fu_576_p1 = ap_sig_allocacmp_ci_2;

assign zext_ln372_fu_630_p1 = lshr_ln1_fu_620_p4;

endmodule //mobilenet_block_accel_pw_row_stage_Pipeline_PW_LOAD_IN
