// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenet_block_accel_dw_row_stage_Pipeline_DW_INIT_LB (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_in_0_AWVALID,
        m_axi_gmem_in_0_AWREADY,
        m_axi_gmem_in_0_AWADDR,
        m_axi_gmem_in_0_AWID,
        m_axi_gmem_in_0_AWLEN,
        m_axi_gmem_in_0_AWSIZE,
        m_axi_gmem_in_0_AWBURST,
        m_axi_gmem_in_0_AWLOCK,
        m_axi_gmem_in_0_AWCACHE,
        m_axi_gmem_in_0_AWPROT,
        m_axi_gmem_in_0_AWQOS,
        m_axi_gmem_in_0_AWREGION,
        m_axi_gmem_in_0_AWUSER,
        m_axi_gmem_in_0_WVALID,
        m_axi_gmem_in_0_WREADY,
        m_axi_gmem_in_0_WDATA,
        m_axi_gmem_in_0_WSTRB,
        m_axi_gmem_in_0_WLAST,
        m_axi_gmem_in_0_WID,
        m_axi_gmem_in_0_WUSER,
        m_axi_gmem_in_0_ARVALID,
        m_axi_gmem_in_0_ARREADY,
        m_axi_gmem_in_0_ARADDR,
        m_axi_gmem_in_0_ARID,
        m_axi_gmem_in_0_ARLEN,
        m_axi_gmem_in_0_ARSIZE,
        m_axi_gmem_in_0_ARBURST,
        m_axi_gmem_in_0_ARLOCK,
        m_axi_gmem_in_0_ARCACHE,
        m_axi_gmem_in_0_ARPROT,
        m_axi_gmem_in_0_ARQOS,
        m_axi_gmem_in_0_ARREGION,
        m_axi_gmem_in_0_ARUSER,
        m_axi_gmem_in_0_RVALID,
        m_axi_gmem_in_0_RREADY,
        m_axi_gmem_in_0_RDATA,
        m_axi_gmem_in_0_RLAST,
        m_axi_gmem_in_0_RID,
        m_axi_gmem_in_0_RFIFONUM,
        m_axi_gmem_in_0_RUSER,
        m_axi_gmem_in_0_RRESP,
        m_axi_gmem_in_0_BVALID,
        m_axi_gmem_in_0_BREADY,
        m_axi_gmem_in_0_BRESP,
        m_axi_gmem_in_0_BID,
        m_axi_gmem_in_0_BUSER,
        line_buf_address0,
        line_buf_ce0,
        line_buf_we0,
        line_buf_d0,
        line_buf_address1,
        line_buf_ce1,
        line_buf_we1,
        line_buf_d1,
        line_buf_1_address0,
        line_buf_1_ce0,
        line_buf_1_we0,
        line_buf_1_d0,
        line_buf_2_address0,
        line_buf_2_ce0,
        line_buf_2_we0,
        line_buf_2_d0,
        empty_59,
        sext_ln181,
        sext_ln181_1,
        zext_ln181,
        input_r,
        sext_ln181_2,
        empty,
        h_start
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_in_0_AWVALID;
input   m_axi_gmem_in_0_AWREADY;
output  [63:0] m_axi_gmem_in_0_AWADDR;
output  [0:0] m_axi_gmem_in_0_AWID;
output  [31:0] m_axi_gmem_in_0_AWLEN;
output  [2:0] m_axi_gmem_in_0_AWSIZE;
output  [1:0] m_axi_gmem_in_0_AWBURST;
output  [1:0] m_axi_gmem_in_0_AWLOCK;
output  [3:0] m_axi_gmem_in_0_AWCACHE;
output  [2:0] m_axi_gmem_in_0_AWPROT;
output  [3:0] m_axi_gmem_in_0_AWQOS;
output  [3:0] m_axi_gmem_in_0_AWREGION;
output  [0:0] m_axi_gmem_in_0_AWUSER;
output   m_axi_gmem_in_0_WVALID;
input   m_axi_gmem_in_0_WREADY;
output  [7:0] m_axi_gmem_in_0_WDATA;
output  [0:0] m_axi_gmem_in_0_WSTRB;
output   m_axi_gmem_in_0_WLAST;
output  [0:0] m_axi_gmem_in_0_WID;
output  [0:0] m_axi_gmem_in_0_WUSER;
output   m_axi_gmem_in_0_ARVALID;
input   m_axi_gmem_in_0_ARREADY;
output  [63:0] m_axi_gmem_in_0_ARADDR;
output  [0:0] m_axi_gmem_in_0_ARID;
output  [31:0] m_axi_gmem_in_0_ARLEN;
output  [2:0] m_axi_gmem_in_0_ARSIZE;
output  [1:0] m_axi_gmem_in_0_ARBURST;
output  [1:0] m_axi_gmem_in_0_ARLOCK;
output  [3:0] m_axi_gmem_in_0_ARCACHE;
output  [2:0] m_axi_gmem_in_0_ARPROT;
output  [3:0] m_axi_gmem_in_0_ARQOS;
output  [3:0] m_axi_gmem_in_0_ARREGION;
output  [0:0] m_axi_gmem_in_0_ARUSER;
input   m_axi_gmem_in_0_RVALID;
output   m_axi_gmem_in_0_RREADY;
input  [7:0] m_axi_gmem_in_0_RDATA;
input   m_axi_gmem_in_0_RLAST;
input  [0:0] m_axi_gmem_in_0_RID;
input  [10:0] m_axi_gmem_in_0_RFIFONUM;
input  [0:0] m_axi_gmem_in_0_RUSER;
input  [1:0] m_axi_gmem_in_0_RRESP;
input   m_axi_gmem_in_0_BVALID;
output   m_axi_gmem_in_0_BREADY;
input  [1:0] m_axi_gmem_in_0_BRESP;
input  [0:0] m_axi_gmem_in_0_BID;
input  [0:0] m_axi_gmem_in_0_BUSER;
output  [6:0] line_buf_address0;
output   line_buf_ce0;
output   line_buf_we0;
output  [7:0] line_buf_d0;
output  [6:0] line_buf_address1;
output   line_buf_ce1;
output   line_buf_we1;
output  [7:0] line_buf_d1;
output  [6:0] line_buf_1_address0;
output   line_buf_1_ce0;
output   line_buf_1_we0;
output  [7:0] line_buf_1_d0;
output  [6:0] line_buf_2_address0;
output   line_buf_2_ce0;
output   line_buf_2_we0;
output  [7:0] line_buf_2_d0;
input  [7:0] empty_59;
input  [31:0] sext_ln181;
input  [30:0] sext_ln181_1;
input  [30:0] zext_ln181;
input  [63:0] input_r;
input  [31:0] sext_ln181_2;
input  [0:0] empty;
input  [30:0] h_start;

reg ap_idle;
reg m_axi_gmem_in_0_ARVALID;
reg[63:0] m_axi_gmem_in_0_ARADDR;
reg m_axi_gmem_in_0_RREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln204_reg_390;
reg   [0:0] cmp25_reg_386;
reg    ap_predicate_op61_readreq_state2;
reg    ap_block_state2_io_grp1;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln204_reg_390_pp0_iter4_reg;
reg    ap_predicate_op81_read_state10;
reg    ap_block_state10_pp0_stage1_iter4_grp3;
reg    ap_block_pp0_stage1_subdone_grp3_done_reg;
reg    ap_block_pp0_stage1_subdone_grp3;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_in_blk_n_AR;
wire    ap_block_pp0_stage0_grp2;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
reg    ap_block_pp0_stage0_subdone;
reg    gmem_in_blk_n_R;
wire    ap_block_pp0_stage0_grp4;
reg    ap_block_pp0_stage0_subdone_grp4_done_reg;
reg    ap_block_pp0_stage0_subdone_grp4;
wire    ap_block_pp0_stage1_grp1;
wire    ap_block_pp0_stage1_grp3;
wire   [0:0] tmp_read_fu_90_p2;
reg    ap_block_state3_io_grp2;
reg    ap_block_state11_pp0_stage0_iter5_grp4;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln181_cast_fu_244_p1;
reg   [63:0] zext_ln181_cast_reg_376;
wire   [63:0] sext_ln181_1_cast_fu_248_p1;
reg   [63:0] sext_ln181_1_cast_reg_381;
wire   [0:0] cmp25_fu_257_p2;
wire   [0:0] icmp_ln204_fu_271_p2;
reg   [0:0] icmp_ln204_reg_390_pp0_iter1_reg;
reg   [0:0] icmp_ln204_reg_390_pp0_iter2_reg;
reg   [0:0] icmp_ln204_reg_390_pp0_iter3_reg;
wire   [63:0] zext_ln204_fu_283_p1;
reg   [63:0] zext_ln204_reg_394;
reg   [63:0] zext_ln204_reg_394_pp0_iter1_reg;
reg   [63:0] zext_ln204_reg_394_pp0_iter2_reg;
reg   [63:0] zext_ln204_reg_394_pp0_iter3_reg;
reg   [63:0] zext_ln204_reg_394_pp0_iter4_reg;
reg   [63:0] zext_ln204_reg_394_pp0_iter5_reg;
reg   [63:0] gmem_in_addr_reg_400;
wire   [32:0] add_ln221_fu_324_p2;
reg   [32:0] add_ln221_reg_406;
reg   [63:0] gmem_in_addr_1_reg_411;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg   [7:0] gmem_in_addr_read_reg_417;
reg    ap_block_pp0_stage1_11001_grp3;
reg   [7:0] gmem_in_addr_1_read_reg_422;
reg    ap_block_pp0_stage0_11001_grp4;
reg   [7:0] ap_phi_mux_cond49_phi_fu_229_p4;
reg   [7:0] ap_phi_reg_pp0_iter5_cond49_reg_226;
reg   [7:0] ap_phi_reg_pp0_iter0_cond49_reg_226;
reg   [7:0] ap_phi_reg_pp0_iter1_cond49_reg_226;
reg   [7:0] ap_phi_reg_pp0_iter2_cond49_reg_226;
reg   [7:0] ap_phi_reg_pp0_iter3_cond49_reg_226;
reg   [7:0] ap_phi_reg_pp0_iter4_cond49_reg_226;
wire    ap_block_pp0_stage0;
wire   [6:0] line_buf_2_addr_gep_fu_184_p3;
wire    ap_block_pp0_stage1_grp0;
wire   [63:0] add_ln219_2_fu_312_p2;
wire   [63:0] add_ln221_2_fu_343_p2;
reg    ap_block_pp0_stage1_11001_grp1;
reg    ap_block_pp0_stage0_11001_grp2;
reg   [6:0] col_fu_80;
wire   [6:0] add_ln204_fu_277_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_col_1;
reg    line_buf_2_we0_local;
reg    line_buf_2_ce0_local;
reg   [6:0] line_buf_2_address0_local;
reg    line_buf_we1_local;
reg    line_buf_ce1_local;
reg    line_buf_we0_local;
reg    line_buf_ce0_local;
reg    line_buf_1_we0_local;
reg   [7:0] line_buf_1_d0_local;
reg    line_buf_1_ce0_local;
reg   [6:0] line_buf_1_address0_local;
reg  signed [32:0] grp_fu_236_p0;
wire  signed [63:0] sext_ln219_fu_301_p1;
wire  signed [63:0] sext_ln221_fu_335_p1;
reg   [30:0] grp_fu_236_p1;
wire  signed [32:0] sext_ln181_2_cast_fu_240_p1;
wire   [32:0] zext_ln204_1_fu_291_p1;
wire   [32:0] add_ln219_fu_295_p2;
wire   [63:0] add_ln219_1_fu_306_p2;
wire   [63:0] grp_fu_236_p2;
wire  signed [32:0] sext_ln181_cast_fu_253_p1;
wire   [63:0] add_ln221_1_fu_339_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage1_11001;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to5;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_606;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 col_fu_80 = 7'd0;
#0 ap_done_reg = 1'b0;
end

mobilenet_block_accel_mul_33s_31ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 33 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 64 ))
mul_33s_31ns_64_1_1_U23(
    .din0(grp_fu_236_p0),
    .din1(grp_fu_236_p1),
    .dout(grp_fu_236_p2)
);

mobilenet_block_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp4)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp3)) begin
                ap_block_pp0_stage1_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln204_fu_271_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            col_fu_80 <= add_ln204_fu_277_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_80 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln221_reg_406 <= add_ln221_fu_324_p2;
        cmp25_reg_386 <= cmp25_fu_257_p2;
        gmem_in_addr_reg_400 <= add_ln219_2_fu_312_p2;
        icmp_ln204_reg_390 <= icmp_ln204_fu_271_p2;
        icmp_ln204_reg_390_pp0_iter1_reg <= icmp_ln204_reg_390;
        icmp_ln204_reg_390_pp0_iter2_reg <= icmp_ln204_reg_390_pp0_iter1_reg;
        icmp_ln204_reg_390_pp0_iter3_reg <= icmp_ln204_reg_390_pp0_iter2_reg;
        icmp_ln204_reg_390_pp0_iter4_reg <= icmp_ln204_reg_390_pp0_iter3_reg;
        sext_ln181_1_cast_reg_381[30 : 0] <= sext_ln181_1_cast_fu_248_p1[30 : 0];
        zext_ln181_cast_reg_376[30 : 0] <= zext_ln181_cast_fu_244_p1[30 : 0];
        zext_ln204_reg_394[6 : 0] <= zext_ln204_fu_283_p1[6 : 0];
        zext_ln204_reg_394_pp0_iter1_reg[6 : 0] <= zext_ln204_reg_394[6 : 0];
        zext_ln204_reg_394_pp0_iter2_reg[6 : 0] <= zext_ln204_reg_394_pp0_iter1_reg[6 : 0];
        zext_ln204_reg_394_pp0_iter3_reg[6 : 0] <= zext_ln204_reg_394_pp0_iter2_reg[6 : 0];
        zext_ln204_reg_394_pp0_iter4_reg[6 : 0] <= zext_ln204_reg_394_pp0_iter3_reg[6 : 0];
        zext_ln204_reg_394_pp0_iter5_reg[6 : 0] <= zext_ln204_reg_394_pp0_iter4_reg[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln204_fu_271_p2 == 1'd0) & (cmp25_fu_257_p2 == 1'd0) & (tmp_read_fu_90_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter0_cond49_reg_226 <= empty_59;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        ap_phi_reg_pp0_iter1_cond49_reg_226 <= ap_phi_reg_pp0_iter0_cond49_reg_226;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        ap_phi_reg_pp0_iter2_cond49_reg_226 <= ap_phi_reg_pp0_iter1_cond49_reg_226;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        ap_phi_reg_pp0_iter3_cond49_reg_226 <= ap_phi_reg_pp0_iter2_cond49_reg_226;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        ap_phi_reg_pp0_iter4_cond49_reg_226 <= ap_phi_reg_pp0_iter3_cond49_reg_226;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        ap_phi_reg_pp0_iter5_cond49_reg_226 <= ap_phi_reg_pp0_iter4_cond49_reg_226;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg))) begin
        gmem_in_addr_1_read_reg_422 <= m_axi_gmem_in_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        gmem_in_addr_1_reg_411 <= add_ln221_2_fu_343_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg))) begin
        gmem_in_addr_read_reg_417 <= m_axi_gmem_in_0_RDATA;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln204_reg_390 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_reg_390_pp0_iter4_reg == 1'd0) & (empty == 1'd0) & (cmp25_reg_386 == 1'd0))) begin
        ap_phi_mux_cond49_phi_fu_229_p4 = gmem_in_addr_read_reg_417;
    end else begin
        ap_phi_mux_cond49_phi_fu_229_p4 = ap_phi_reg_pp0_iter5_cond49_reg_226;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_col_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_col_1 = col_fu_80;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (ap_predicate_op61_readreq_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (cmp25_reg_386 == 1'd0)))) begin
        gmem_in_blk_n_AR = m_axi_gmem_in_0_ARREADY;
    end else begin
        gmem_in_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (1'b0 == ap_block_pp0_stage0_grp4) & (cmp25_reg_386 == 1'd0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op81_read_state10 == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)))) begin
        gmem_in_blk_n_R = m_axi_gmem_in_0_RVALID;
    end else begin
        gmem_in_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        grp_fu_236_p0 = sext_ln221_fu_335_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_236_p0 = sext_ln219_fu_301_p1;
    end else begin
        grp_fu_236_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        grp_fu_236_p1 = sext_ln181_1_cast_reg_381;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_236_p1 = sext_ln181_1_cast_fu_248_p1;
    end else begin
        grp_fu_236_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        line_buf_1_address0_local = zext_ln204_reg_394_pp0_iter5_reg;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        line_buf_1_address0_local = zext_ln204_fu_283_p1;
    end else begin
        line_buf_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)))) begin
        line_buf_1_ce0_local = 1'b1;
    end else begin
        line_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        line_buf_1_d0_local = gmem_in_addr_1_read_reg_422;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        line_buf_1_d0_local = empty_59;
    end else begin
        line_buf_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln204_fu_271_p2 == 1'd0) & (cmp25_fu_257_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (cmp25_reg_386 == 1'd0)))) begin
        line_buf_1_we0_local = 1'b1;
    end else begin
        line_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_606)) begin
        if ((cmp25_fu_257_p2 == 1'd1)) begin
            line_buf_2_address0_local = line_buf_2_addr_gep_fu_184_p3;
        end else if ((cmp25_fu_257_p2 == 1'd0)) begin
            line_buf_2_address0_local = zext_ln204_fu_283_p1;
        end else begin
            line_buf_2_address0_local = 'bx;
        end
    end else begin
        line_buf_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln204_fu_271_p2 == 1'd0) & (cmp25_fu_257_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln204_fu_271_p2 == 1'd0) & (cmp25_fu_257_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line_buf_2_ce0_local = 1'b1;
    end else begin
        line_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln204_fu_271_p2 == 1'd0) & (cmp25_fu_257_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln204_fu_271_p2 == 1'd0) & (cmp25_fu_257_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line_buf_2_we0_local = 1'b1;
    end else begin
        line_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_ce0_local = 1'b1;
    end else begin
        line_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_ce1_local = 1'b1;
    end else begin
        line_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp25_reg_386 == 1'd0))) begin
        line_buf_we0_local = 1'b1;
    end else begin
        line_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln204_fu_271_p2 == 1'd0) & (cmp25_fu_257_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_we1_local = 1'b1;
    end else begin
        line_buf_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (cmp25_reg_386 == 1'd0))) begin
        m_axi_gmem_in_0_ARADDR = gmem_in_addr_1_reg_411;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (ap_predicate_op61_readreq_state2 == 1'b1))) begin
        m_axi_gmem_in_0_ARADDR = gmem_in_addr_reg_400;
    end else begin
        m_axi_gmem_in_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (ap_predicate_op61_readreq_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (cmp25_reg_386 == 1'd0)))) begin
        m_axi_gmem_in_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_in_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (cmp25_reg_386 == 1'd0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op81_read_state10 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)))) begin
        m_axi_gmem_in_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_in_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln204_fu_277_p2 = (ap_sig_allocacmp_col_1 + 7'd1);

assign add_ln219_1_fu_306_p2 = (zext_ln181_cast_fu_244_p1 + input_r);

assign add_ln219_2_fu_312_p2 = (add_ln219_1_fu_306_p2 + grp_fu_236_p2);

assign add_ln219_fu_295_p2 = ($signed(sext_ln181_2_cast_fu_240_p1) + $signed(zext_ln204_1_fu_291_p1));

assign add_ln221_1_fu_339_p2 = (zext_ln181_cast_reg_376 + input_r);

assign add_ln221_2_fu_343_p2 = (add_ln221_1_fu_339_p2 + grp_fu_236_p2);

assign add_ln221_fu_324_p2 = ($signed(sext_ln181_cast_fu_253_p1) + $signed(zext_ln204_1_fu_291_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter5_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp4 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter5_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg));
end

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter5_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp4 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter5_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter4_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)) | ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp3 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter4_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter4_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg)) | ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp3 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter4_grp3) & (1'b0 == ap_block_pp0_stage1_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter4_grp3 = ((m_axi_gmem_in_0_RVALID == 1'b0) & (ap_predicate_op81_read_state10 == 1'b1));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter5_grp4 = ((m_axi_gmem_in_0_RVALID == 1'b0) & (cmp25_reg_386 == 1'd0));
end

always @ (*) begin
    ap_block_state2_io_grp1 = ((m_axi_gmem_in_0_ARREADY == 1'b0) & (ap_predicate_op61_readreq_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_io_grp2 = ((m_axi_gmem_in_0_ARREADY == 1'b0) & (cmp25_reg_386 == 1'd0));
end

always @ (*) begin
    ap_condition_606 = ((icmp_ln204_fu_271_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

always @ (*) begin
    ap_predicate_op61_readreq_state2 = ((empty == 1'd0) & (cmp25_reg_386 == 1'd0) & (icmp_ln204_reg_390 == 1'd0));
end

always @ (*) begin
    ap_predicate_op81_read_state10 = ((icmp_ln204_reg_390_pp0_iter4_reg == 1'd0) & (empty == 1'd0) & (cmp25_reg_386 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign cmp25_fu_257_p2 = ((h_start == 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln204_fu_271_p2 = ((ap_sig_allocacmp_col_1 == 7'd112) ? 1'b1 : 1'b0);

assign line_buf_1_address0 = line_buf_1_address0_local;

assign line_buf_1_ce0 = line_buf_1_ce0_local;

assign line_buf_1_d0 = line_buf_1_d0_local;

assign line_buf_1_we0 = line_buf_1_we0_local;

assign line_buf_2_addr_gep_fu_184_p3 = zext_ln204_fu_283_p1;

assign line_buf_2_address0 = line_buf_2_address0_local;

assign line_buf_2_ce0 = line_buf_2_ce0_local;

assign line_buf_2_d0 = empty_59;

assign line_buf_2_we0 = line_buf_2_we0_local;

assign line_buf_address0 = zext_ln204_reg_394_pp0_iter4_reg;

assign line_buf_address1 = zext_ln204_fu_283_p1;

assign line_buf_ce0 = line_buf_ce0_local;

assign line_buf_ce1 = line_buf_ce1_local;

assign line_buf_d0 = ap_phi_mux_cond49_phi_fu_229_p4;

assign line_buf_d1 = empty_59;

assign line_buf_we0 = line_buf_we0_local;

assign line_buf_we1 = line_buf_we1_local;

assign m_axi_gmem_in_0_ARBURST = 2'd0;

assign m_axi_gmem_in_0_ARCACHE = 4'd0;

assign m_axi_gmem_in_0_ARID = 1'd0;

assign m_axi_gmem_in_0_ARLEN = 64'd1;

assign m_axi_gmem_in_0_ARLOCK = 2'd0;

assign m_axi_gmem_in_0_ARPROT = 3'd0;

assign m_axi_gmem_in_0_ARQOS = 4'd0;

assign m_axi_gmem_in_0_ARREGION = 4'd0;

assign m_axi_gmem_in_0_ARSIZE = 3'd0;

assign m_axi_gmem_in_0_ARUSER = 1'd0;

assign m_axi_gmem_in_0_AWADDR = 64'd0;

assign m_axi_gmem_in_0_AWBURST = 2'd0;

assign m_axi_gmem_in_0_AWCACHE = 4'd0;

assign m_axi_gmem_in_0_AWID = 1'd0;

assign m_axi_gmem_in_0_AWLEN = 32'd0;

assign m_axi_gmem_in_0_AWLOCK = 2'd0;

assign m_axi_gmem_in_0_AWPROT = 3'd0;

assign m_axi_gmem_in_0_AWQOS = 4'd0;

assign m_axi_gmem_in_0_AWREGION = 4'd0;

assign m_axi_gmem_in_0_AWSIZE = 3'd0;

assign m_axi_gmem_in_0_AWUSER = 1'd0;

assign m_axi_gmem_in_0_AWVALID = 1'b0;

assign m_axi_gmem_in_0_BREADY = 1'b0;

assign m_axi_gmem_in_0_WDATA = 8'd0;

assign m_axi_gmem_in_0_WID = 1'd0;

assign m_axi_gmem_in_0_WLAST = 1'b0;

assign m_axi_gmem_in_0_WSTRB = 1'd0;

assign m_axi_gmem_in_0_WUSER = 1'd0;

assign m_axi_gmem_in_0_WVALID = 1'b0;

assign sext_ln181_1_cast_fu_248_p1 = sext_ln181_1;

assign sext_ln181_2_cast_fu_240_p1 = $signed(sext_ln181_2);

assign sext_ln181_cast_fu_253_p1 = $signed(sext_ln181);

assign sext_ln219_fu_301_p1 = $signed(add_ln219_fu_295_p2);

assign sext_ln221_fu_335_p1 = $signed(add_ln221_reg_406);

assign tmp_read_fu_90_p2 = empty;

assign zext_ln181_cast_fu_244_p1 = zext_ln181;

assign zext_ln204_1_fu_291_p1 = ap_sig_allocacmp_col_1;

assign zext_ln204_fu_283_p1 = ap_sig_allocacmp_col_1;

always @ (posedge ap_clk) begin
    zext_ln181_cast_reg_376[63:31] <= 33'b000000000000000000000000000000000;
    sext_ln181_1_cast_reg_381[63:31] <= 33'b000000000000000000000000000000000;
    zext_ln204_reg_394[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln204_reg_394_pp0_iter1_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln204_reg_394_pp0_iter2_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln204_reg_394_pp0_iter3_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln204_reg_394_pp0_iter4_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln204_reg_394_pp0_iter5_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //mobilenet_block_accel_dw_row_stage_Pipeline_DW_INIT_LB
