-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mobilenet_block_accel_dataflow_parent_loop_proc is
port (
    add1 : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_in_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_in_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_in_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_in_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_in_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_in_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_in_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_in_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_in_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_r : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_dw_w_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_dw_w_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_dw_w_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_dw_w_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_dw_w_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_dw_w_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_dw_w_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_dw_w_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_dw_w_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_dw_w_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_dw_w_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_dw_w_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    dw_weights : IN STD_LOGIC_VECTOR (63 downto 0);
    dw_bias : IN STD_LOGIC_VECTOR (63 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    c_in : IN STD_LOGIC_VECTOR (31 downto 0);
    dw_in_zp : IN STD_LOGIC_VECTOR (31 downto 0);
    dw_w_zp : IN STD_LOGIC_VECTOR (31 downto 0);
    dw_out_zp : IN STD_LOGIC_VECTOR (31 downto 0);
    dw_multiplier : IN STD_LOGIC_VECTOR (31 downto 0);
    dw_shift : IN STD_LOGIC_VECTOR (31 downto 0);
    dw_apply_relu6 : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_pw_w_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_pw_w_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_pw_w_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_pw_w_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_pw_w_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_pw_w_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_pw_w_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_pw_w_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_pw_w_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_pw_w_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_pw_w_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_pw_w_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_pw_w_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_pw_w_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_pw_w_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_pw_w_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_pw_w_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_pw_w_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_pw_w_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_pw_w_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_pw_w_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_pw_w_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_pw_w_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_pw_w_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_pw_w_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_pw_w_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_pw_w_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_pw_w_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_pw_w_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_pw_w_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_pw_w_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_pw_w_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_pw_w_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_pw_w_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_pw_w_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_pw_w_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_pw_w_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_pw_w_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_pw_w_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_pw_w_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_pw_w_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_pw_w_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_pw_w_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_pw_w_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_pw_w_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_pw_w_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    pw_weights : IN STD_LOGIC_VECTOR (63 downto 0);
    pw_bias : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_out_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_out_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_out_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_out_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_out_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_out_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_out_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_out_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_out_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_out_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_out_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_out_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_out_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_out_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_out_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_out_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_out_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_out_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    output_r : IN STD_LOGIC_VECTOR (63 downto 0);
    c_out : IN STD_LOGIC_VECTOR (31 downto 0);
    pw_act_zp : IN STD_LOGIC_VECTOR (15 downto 0);
    pw_wgt_zp : IN STD_LOGIC_VECTOR (15 downto 0);
    pw_out_zp : IN STD_LOGIC_VECTOR (31 downto 0);
    pw_M_mantissa : IN STD_LOGIC_VECTOR (31 downto 0);
    pw_M_shift : IN STD_LOGIC_VECTOR (31 downto 0);
    pw_use_bias : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    input_r_ap_vld : IN STD_LOGIC;
    dw_weights_ap_vld : IN STD_LOGIC;
    dw_bias_ap_vld : IN STD_LOGIC;
    height_ap_vld : IN STD_LOGIC;
    width_ap_vld : IN STD_LOGIC;
    c_in_ap_vld : IN STD_LOGIC;
    dw_in_zp_ap_vld : IN STD_LOGIC;
    dw_w_zp_ap_vld : IN STD_LOGIC;
    dw_out_zp_ap_vld : IN STD_LOGIC;
    dw_multiplier_ap_vld : IN STD_LOGIC;
    dw_shift_ap_vld : IN STD_LOGIC;
    dw_apply_relu6_ap_vld : IN STD_LOGIC;
    pw_weights_ap_vld : IN STD_LOGIC;
    pw_bias_ap_vld : IN STD_LOGIC;
    output_r_ap_vld : IN STD_LOGIC;
    c_out_ap_vld : IN STD_LOGIC;
    pw_act_zp_ap_vld : IN STD_LOGIC;
    pw_wgt_zp_ap_vld : IN STD_LOGIC;
    pw_out_zp_ap_vld : IN STD_LOGIC;
    pw_M_mantissa_ap_vld : IN STD_LOGIC;
    pw_M_shift_ap_vld : IN STD_LOGIC;
    pw_use_bias_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of mobilenet_block_accel_dataflow_parent_loop_proc is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal dataflow_in_loop_TILE_LOOP_1_U0_tile_0 : STD_LOGIC_VECTOR (30 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_TILE_LOOP_1_U0_ap_continue : STD_LOGIC;
    signal loop_dataflow_input_count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal loop_dataflow_output_count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bound_minus_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mobilenet_block_accel_dataflow_in_loop_TILE_LOOP_1 IS
    port (
        tile_0 : IN STD_LOGIC_VECTOR (30 downto 0);
        m_axi_gmem_in_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_in_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_in_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_in_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_in_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_in_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_in_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_in_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_in_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_in_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_in_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_in_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_in_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_in_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_in_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_in_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_in_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_in_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem_in_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_in_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_in_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_in_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_in_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        input_r : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_dw_w_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_dw_w_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_dw_w_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_dw_w_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_dw_w_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_dw_w_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_dw_w_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_dw_w_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_dw_w_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_dw_w_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_dw_w_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_dw_w_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_dw_w_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_dw_w_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_dw_w_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_dw_w_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_dw_w_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_dw_w_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_dw_w_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_dw_w_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_dw_w_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_dw_w_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_dw_w_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_dw_w_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_dw_w_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_dw_w_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_dw_w_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_dw_w_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_dw_w_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_dw_w_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_dw_w_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_dw_w_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_dw_w_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_dw_w_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_dw_w_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_dw_w_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_dw_w_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_dw_w_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_dw_w_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_dw_w_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_dw_w_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_dw_w_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_dw_w_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_dw_w_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_dw_w_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_dw_w_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        dw_weights : IN STD_LOGIC_VECTOR (63 downto 0);
        dw_bias : IN STD_LOGIC_VECTOR (63 downto 0);
        height : IN STD_LOGIC_VECTOR (31 downto 0);
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        c_in : IN STD_LOGIC_VECTOR (31 downto 0);
        dw_in_zp : IN STD_LOGIC_VECTOR (31 downto 0);
        dw_w_zp : IN STD_LOGIC_VECTOR (31 downto 0);
        dw_out_zp : IN STD_LOGIC_VECTOR (31 downto 0);
        dw_multiplier : IN STD_LOGIC_VECTOR (31 downto 0);
        dw_shift : IN STD_LOGIC_VECTOR (31 downto 0);
        dw_apply_relu6 : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_pw_w_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_pw_w_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_pw_w_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_pw_w_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_pw_w_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_pw_w_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_pw_w_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_pw_w_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_pw_w_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_pw_w_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_pw_w_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_pw_w_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_pw_w_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_pw_w_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_pw_w_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_pw_w_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_pw_w_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_pw_w_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_pw_w_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_pw_w_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_pw_w_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_pw_w_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_pw_w_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_pw_w_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_pw_w_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_pw_w_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_pw_w_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_pw_w_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_pw_w_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_pw_w_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_pw_w_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_pw_w_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_pw_w_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_pw_w_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_pw_w_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_pw_w_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_pw_w_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_pw_w_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_pw_w_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_pw_w_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_pw_w_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_pw_w_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_pw_w_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_pw_w_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_pw_w_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_pw_w_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        pw_weights : IN STD_LOGIC_VECTOR (63 downto 0);
        pw_bias : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_out_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_out_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_out_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_out_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_out_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_out_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_out_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_out_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_out_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_out_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_out_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_out_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_out_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_out_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_out_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_out_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_out_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_out_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_out_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_out_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_out_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_out_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem_out_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_out_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_out_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_out_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_out_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        output_r : IN STD_LOGIC_VECTOR (63 downto 0);
        c_out : IN STD_LOGIC_VECTOR (31 downto 0);
        pw_act_zp : IN STD_LOGIC_VECTOR (15 downto 0);
        pw_wgt_zp : IN STD_LOGIC_VECTOR (15 downto 0);
        pw_out_zp : IN STD_LOGIC_VECTOR (31 downto 0);
        pw_M_mantissa : IN STD_LOGIC_VECTOR (31 downto 0);
        pw_M_shift : IN STD_LOGIC_VECTOR (31 downto 0);
        pw_use_bias : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        tile_0_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        input_r_ap_vld : IN STD_LOGIC;
        dw_weights_ap_vld : IN STD_LOGIC;
        dw_bias_ap_vld : IN STD_LOGIC;
        height_ap_vld : IN STD_LOGIC;
        width_ap_vld : IN STD_LOGIC;
        c_in_ap_vld : IN STD_LOGIC;
        dw_in_zp_ap_vld : IN STD_LOGIC;
        dw_w_zp_ap_vld : IN STD_LOGIC;
        dw_out_zp_ap_vld : IN STD_LOGIC;
        dw_multiplier_ap_vld : IN STD_LOGIC;
        dw_shift_ap_vld : IN STD_LOGIC;
        dw_apply_relu6_ap_vld : IN STD_LOGIC;
        pw_weights_ap_vld : IN STD_LOGIC;
        pw_bias_ap_vld : IN STD_LOGIC;
        output_r_ap_vld : IN STD_LOGIC;
        c_out_ap_vld : IN STD_LOGIC;
        pw_act_zp_ap_vld : IN STD_LOGIC;
        pw_wgt_zp_ap_vld : IN STD_LOGIC;
        pw_out_zp_ap_vld : IN STD_LOGIC;
        pw_M_mantissa_ap_vld : IN STD_LOGIC;
        pw_M_shift_ap_vld : IN STD_LOGIC;
        pw_use_bias_ap_vld : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    dataflow_in_loop_TILE_LOOP_1_U0 : component mobilenet_block_accel_dataflow_in_loop_TILE_LOOP_1
    port map (
        tile_0 => dataflow_in_loop_TILE_LOOP_1_U0_tile_0,
        m_axi_gmem_in_0_AWVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWVALID,
        m_axi_gmem_in_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_in_0_AWADDR => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWADDR,
        m_axi_gmem_in_0_AWID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWID,
        m_axi_gmem_in_0_AWLEN => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWLEN,
        m_axi_gmem_in_0_AWSIZE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWSIZE,
        m_axi_gmem_in_0_AWBURST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWBURST,
        m_axi_gmem_in_0_AWLOCK => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWLOCK,
        m_axi_gmem_in_0_AWCACHE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWCACHE,
        m_axi_gmem_in_0_AWPROT => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWPROT,
        m_axi_gmem_in_0_AWQOS => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWQOS,
        m_axi_gmem_in_0_AWREGION => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWREGION,
        m_axi_gmem_in_0_AWUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_AWUSER,
        m_axi_gmem_in_0_WVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WVALID,
        m_axi_gmem_in_0_WREADY => ap_const_logic_0,
        m_axi_gmem_in_0_WDATA => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WDATA,
        m_axi_gmem_in_0_WSTRB => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WSTRB,
        m_axi_gmem_in_0_WLAST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WLAST,
        m_axi_gmem_in_0_WID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WID,
        m_axi_gmem_in_0_WUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_WUSER,
        m_axi_gmem_in_0_ARVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARVALID,
        m_axi_gmem_in_0_ARREADY => m_axi_gmem_in_0_ARREADY,
        m_axi_gmem_in_0_ARADDR => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARADDR,
        m_axi_gmem_in_0_ARID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARID,
        m_axi_gmem_in_0_ARLEN => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARLEN,
        m_axi_gmem_in_0_ARSIZE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARSIZE,
        m_axi_gmem_in_0_ARBURST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARBURST,
        m_axi_gmem_in_0_ARLOCK => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARLOCK,
        m_axi_gmem_in_0_ARCACHE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARCACHE,
        m_axi_gmem_in_0_ARPROT => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARPROT,
        m_axi_gmem_in_0_ARQOS => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARQOS,
        m_axi_gmem_in_0_ARREGION => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARREGION,
        m_axi_gmem_in_0_ARUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARUSER,
        m_axi_gmem_in_0_RVALID => m_axi_gmem_in_0_RVALID,
        m_axi_gmem_in_0_RREADY => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_RREADY,
        m_axi_gmem_in_0_RDATA => m_axi_gmem_in_0_RDATA,
        m_axi_gmem_in_0_RLAST => m_axi_gmem_in_0_RLAST,
        m_axi_gmem_in_0_RID => m_axi_gmem_in_0_RID,
        m_axi_gmem_in_0_RFIFONUM => m_axi_gmem_in_0_RFIFONUM,
        m_axi_gmem_in_0_RUSER => m_axi_gmem_in_0_RUSER,
        m_axi_gmem_in_0_RRESP => m_axi_gmem_in_0_RRESP,
        m_axi_gmem_in_0_BVALID => ap_const_logic_0,
        m_axi_gmem_in_0_BREADY => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_BREADY,
        m_axi_gmem_in_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_in_0_BID => ap_const_lv1_0,
        m_axi_gmem_in_0_BUSER => ap_const_lv1_0,
        input_r => input_r,
        m_axi_gmem_dw_w_0_AWVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWVALID,
        m_axi_gmem_dw_w_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_dw_w_0_AWADDR => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWADDR,
        m_axi_gmem_dw_w_0_AWID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWID,
        m_axi_gmem_dw_w_0_AWLEN => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWLEN,
        m_axi_gmem_dw_w_0_AWSIZE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWSIZE,
        m_axi_gmem_dw_w_0_AWBURST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWBURST,
        m_axi_gmem_dw_w_0_AWLOCK => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWLOCK,
        m_axi_gmem_dw_w_0_AWCACHE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWCACHE,
        m_axi_gmem_dw_w_0_AWPROT => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWPROT,
        m_axi_gmem_dw_w_0_AWQOS => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWQOS,
        m_axi_gmem_dw_w_0_AWREGION => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWREGION,
        m_axi_gmem_dw_w_0_AWUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_AWUSER,
        m_axi_gmem_dw_w_0_WVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WVALID,
        m_axi_gmem_dw_w_0_WREADY => ap_const_logic_0,
        m_axi_gmem_dw_w_0_WDATA => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WDATA,
        m_axi_gmem_dw_w_0_WSTRB => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WSTRB,
        m_axi_gmem_dw_w_0_WLAST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WLAST,
        m_axi_gmem_dw_w_0_WID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WID,
        m_axi_gmem_dw_w_0_WUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_WUSER,
        m_axi_gmem_dw_w_0_ARVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARVALID,
        m_axi_gmem_dw_w_0_ARREADY => m_axi_gmem_dw_w_0_ARREADY,
        m_axi_gmem_dw_w_0_ARADDR => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARADDR,
        m_axi_gmem_dw_w_0_ARID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARID,
        m_axi_gmem_dw_w_0_ARLEN => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARLEN,
        m_axi_gmem_dw_w_0_ARSIZE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARSIZE,
        m_axi_gmem_dw_w_0_ARBURST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARBURST,
        m_axi_gmem_dw_w_0_ARLOCK => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARLOCK,
        m_axi_gmem_dw_w_0_ARCACHE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARCACHE,
        m_axi_gmem_dw_w_0_ARPROT => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARPROT,
        m_axi_gmem_dw_w_0_ARQOS => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARQOS,
        m_axi_gmem_dw_w_0_ARREGION => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARREGION,
        m_axi_gmem_dw_w_0_ARUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARUSER,
        m_axi_gmem_dw_w_0_RVALID => m_axi_gmem_dw_w_0_RVALID,
        m_axi_gmem_dw_w_0_RREADY => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_RREADY,
        m_axi_gmem_dw_w_0_RDATA => m_axi_gmem_dw_w_0_RDATA,
        m_axi_gmem_dw_w_0_RLAST => m_axi_gmem_dw_w_0_RLAST,
        m_axi_gmem_dw_w_0_RID => m_axi_gmem_dw_w_0_RID,
        m_axi_gmem_dw_w_0_RFIFONUM => m_axi_gmem_dw_w_0_RFIFONUM,
        m_axi_gmem_dw_w_0_RUSER => m_axi_gmem_dw_w_0_RUSER,
        m_axi_gmem_dw_w_0_RRESP => m_axi_gmem_dw_w_0_RRESP,
        m_axi_gmem_dw_w_0_BVALID => ap_const_logic_0,
        m_axi_gmem_dw_w_0_BREADY => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_BREADY,
        m_axi_gmem_dw_w_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_dw_w_0_BID => ap_const_lv1_0,
        m_axi_gmem_dw_w_0_BUSER => ap_const_lv1_0,
        dw_weights => dw_weights,
        dw_bias => dw_bias,
        height => height,
        width => width,
        c_in => c_in,
        dw_in_zp => dw_in_zp,
        dw_w_zp => dw_w_zp,
        dw_out_zp => dw_out_zp,
        dw_multiplier => dw_multiplier,
        dw_shift => dw_shift,
        dw_apply_relu6 => dw_apply_relu6,
        m_axi_gmem_pw_w_0_AWVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWVALID,
        m_axi_gmem_pw_w_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_pw_w_0_AWADDR => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWADDR,
        m_axi_gmem_pw_w_0_AWID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWID,
        m_axi_gmem_pw_w_0_AWLEN => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWLEN,
        m_axi_gmem_pw_w_0_AWSIZE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWSIZE,
        m_axi_gmem_pw_w_0_AWBURST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWBURST,
        m_axi_gmem_pw_w_0_AWLOCK => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWLOCK,
        m_axi_gmem_pw_w_0_AWCACHE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWCACHE,
        m_axi_gmem_pw_w_0_AWPROT => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWPROT,
        m_axi_gmem_pw_w_0_AWQOS => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWQOS,
        m_axi_gmem_pw_w_0_AWREGION => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWREGION,
        m_axi_gmem_pw_w_0_AWUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_AWUSER,
        m_axi_gmem_pw_w_0_WVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WVALID,
        m_axi_gmem_pw_w_0_WREADY => ap_const_logic_0,
        m_axi_gmem_pw_w_0_WDATA => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WDATA,
        m_axi_gmem_pw_w_0_WSTRB => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WSTRB,
        m_axi_gmem_pw_w_0_WLAST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WLAST,
        m_axi_gmem_pw_w_0_WID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WID,
        m_axi_gmem_pw_w_0_WUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_WUSER,
        m_axi_gmem_pw_w_0_ARVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARVALID,
        m_axi_gmem_pw_w_0_ARREADY => m_axi_gmem_pw_w_0_ARREADY,
        m_axi_gmem_pw_w_0_ARADDR => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARADDR,
        m_axi_gmem_pw_w_0_ARID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARID,
        m_axi_gmem_pw_w_0_ARLEN => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARLEN,
        m_axi_gmem_pw_w_0_ARSIZE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARSIZE,
        m_axi_gmem_pw_w_0_ARBURST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARBURST,
        m_axi_gmem_pw_w_0_ARLOCK => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARLOCK,
        m_axi_gmem_pw_w_0_ARCACHE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARCACHE,
        m_axi_gmem_pw_w_0_ARPROT => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARPROT,
        m_axi_gmem_pw_w_0_ARQOS => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARQOS,
        m_axi_gmem_pw_w_0_ARREGION => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARREGION,
        m_axi_gmem_pw_w_0_ARUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARUSER,
        m_axi_gmem_pw_w_0_RVALID => m_axi_gmem_pw_w_0_RVALID,
        m_axi_gmem_pw_w_0_RREADY => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_RREADY,
        m_axi_gmem_pw_w_0_RDATA => m_axi_gmem_pw_w_0_RDATA,
        m_axi_gmem_pw_w_0_RLAST => m_axi_gmem_pw_w_0_RLAST,
        m_axi_gmem_pw_w_0_RID => m_axi_gmem_pw_w_0_RID,
        m_axi_gmem_pw_w_0_RFIFONUM => m_axi_gmem_pw_w_0_RFIFONUM,
        m_axi_gmem_pw_w_0_RUSER => m_axi_gmem_pw_w_0_RUSER,
        m_axi_gmem_pw_w_0_RRESP => m_axi_gmem_pw_w_0_RRESP,
        m_axi_gmem_pw_w_0_BVALID => ap_const_logic_0,
        m_axi_gmem_pw_w_0_BREADY => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_BREADY,
        m_axi_gmem_pw_w_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_pw_w_0_BID => ap_const_lv1_0,
        m_axi_gmem_pw_w_0_BUSER => ap_const_lv1_0,
        pw_weights => pw_weights,
        pw_bias => pw_bias,
        m_axi_gmem_out_0_AWVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWVALID,
        m_axi_gmem_out_0_AWREADY => m_axi_gmem_out_0_AWREADY,
        m_axi_gmem_out_0_AWADDR => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWADDR,
        m_axi_gmem_out_0_AWID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWID,
        m_axi_gmem_out_0_AWLEN => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWLEN,
        m_axi_gmem_out_0_AWSIZE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWSIZE,
        m_axi_gmem_out_0_AWBURST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWBURST,
        m_axi_gmem_out_0_AWLOCK => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWLOCK,
        m_axi_gmem_out_0_AWCACHE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWCACHE,
        m_axi_gmem_out_0_AWPROT => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWPROT,
        m_axi_gmem_out_0_AWQOS => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWQOS,
        m_axi_gmem_out_0_AWREGION => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWREGION,
        m_axi_gmem_out_0_AWUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWUSER,
        m_axi_gmem_out_0_WVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WVALID,
        m_axi_gmem_out_0_WREADY => m_axi_gmem_out_0_WREADY,
        m_axi_gmem_out_0_WDATA => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WDATA,
        m_axi_gmem_out_0_WSTRB => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WSTRB,
        m_axi_gmem_out_0_WLAST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WLAST,
        m_axi_gmem_out_0_WID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WID,
        m_axi_gmem_out_0_WUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WUSER,
        m_axi_gmem_out_0_ARVALID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARVALID,
        m_axi_gmem_out_0_ARREADY => ap_const_logic_0,
        m_axi_gmem_out_0_ARADDR => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARADDR,
        m_axi_gmem_out_0_ARID => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARID,
        m_axi_gmem_out_0_ARLEN => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARLEN,
        m_axi_gmem_out_0_ARSIZE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARSIZE,
        m_axi_gmem_out_0_ARBURST => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARBURST,
        m_axi_gmem_out_0_ARLOCK => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARLOCK,
        m_axi_gmem_out_0_ARCACHE => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARCACHE,
        m_axi_gmem_out_0_ARPROT => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARPROT,
        m_axi_gmem_out_0_ARQOS => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARQOS,
        m_axi_gmem_out_0_ARREGION => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARREGION,
        m_axi_gmem_out_0_ARUSER => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_ARUSER,
        m_axi_gmem_out_0_RVALID => ap_const_logic_0,
        m_axi_gmem_out_0_RREADY => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_RREADY,
        m_axi_gmem_out_0_RDATA => ap_const_lv8_0,
        m_axi_gmem_out_0_RLAST => ap_const_logic_0,
        m_axi_gmem_out_0_RID => ap_const_lv1_0,
        m_axi_gmem_out_0_RFIFONUM => ap_const_lv11_0,
        m_axi_gmem_out_0_RUSER => ap_const_lv1_0,
        m_axi_gmem_out_0_RRESP => ap_const_lv2_0,
        m_axi_gmem_out_0_BVALID => m_axi_gmem_out_0_BVALID,
        m_axi_gmem_out_0_BREADY => dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_BREADY,
        m_axi_gmem_out_0_BRESP => m_axi_gmem_out_0_BRESP,
        m_axi_gmem_out_0_BID => m_axi_gmem_out_0_BID,
        m_axi_gmem_out_0_BUSER => m_axi_gmem_out_0_BUSER,
        output_r => output_r,
        c_out => c_out,
        pw_act_zp => pw_act_zp,
        pw_wgt_zp => pw_wgt_zp,
        pw_out_zp => pw_out_zp,
        pw_M_mantissa => pw_M_mantissa,
        pw_M_shift => pw_M_shift,
        pw_use_bias => pw_use_bias,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        tile_0_ap_vld => ap_const_logic_0,
        ap_start => dataflow_in_loop_TILE_LOOP_1_U0_ap_start,
        input_r_ap_vld => input_r_ap_vld,
        dw_weights_ap_vld => dw_weights_ap_vld,
        dw_bias_ap_vld => dw_bias_ap_vld,
        height_ap_vld => height_ap_vld,
        width_ap_vld => width_ap_vld,
        c_in_ap_vld => c_in_ap_vld,
        dw_in_zp_ap_vld => dw_in_zp_ap_vld,
        dw_w_zp_ap_vld => dw_w_zp_ap_vld,
        dw_out_zp_ap_vld => dw_out_zp_ap_vld,
        dw_multiplier_ap_vld => dw_multiplier_ap_vld,
        dw_shift_ap_vld => dw_shift_ap_vld,
        dw_apply_relu6_ap_vld => dw_apply_relu6_ap_vld,
        pw_weights_ap_vld => pw_weights_ap_vld,
        pw_bias_ap_vld => pw_bias_ap_vld,
        output_r_ap_vld => output_r_ap_vld,
        c_out_ap_vld => c_out_ap_vld,
        pw_act_zp_ap_vld => pw_act_zp_ap_vld,
        pw_wgt_zp_ap_vld => pw_wgt_zp_ap_vld,
        pw_out_zp_ap_vld => pw_out_zp_ap_vld,
        pw_M_mantissa_ap_vld => pw_M_mantissa_ap_vld,
        pw_M_shift_ap_vld => pw_M_shift_ap_vld,
        pw_use_bias_ap_vld => pw_use_bias_ap_vld,
        ap_done => dataflow_in_loop_TILE_LOOP_1_U0_ap_done,
        ap_ready => dataflow_in_loop_TILE_LOOP_1_U0_ap_ready,
        ap_idle => dataflow_in_loop_TILE_LOOP_1_U0_ap_idle,
        ap_continue => dataflow_in_loop_TILE_LOOP_1_U0_ap_continue);





    loop_dataflow_input_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_input_count <= ap_const_lv32_0;
            else
                if ((not((loop_dataflow_input_count = bound_minus_1)) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_TILE_LOOP_1_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= std_logic_vector(unsigned(loop_dataflow_input_count) + unsigned(ap_const_lv32_1));
                elsif (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_TILE_LOOP_1_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= ap_const_lv32_0;
                end if; 
            end if;
        end if;
    end process;


    loop_dataflow_output_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_output_count <= ap_const_lv32_0;
            else
                if ((not((loop_dataflow_output_count = bound_minus_1)) and (dataflow_in_loop_TILE_LOOP_1_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_TILE_LOOP_1_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= std_logic_vector(unsigned(loop_dataflow_output_count) + unsigned(ap_const_lv32_1));
                elsif (((loop_dataflow_output_count = bound_minus_1) and (dataflow_in_loop_TILE_LOOP_1_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_TILE_LOOP_1_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= ap_const_lv32_0;
                end if; 
            end if;
        end if;
    end process;


    ap_done_assign_proc : process(dataflow_in_loop_TILE_LOOP_1_U0_ap_done, loop_dataflow_output_count, bound_minus_1)
    begin
        if (((loop_dataflow_output_count = bound_minus_1) and (dataflow_in_loop_TILE_LOOP_1_U0_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(dataflow_in_loop_TILE_LOOP_1_U0_ap_idle, ap_start, loop_dataflow_output_count)
    begin
        if (((loop_dataflow_output_count = ap_const_lv32_0) and (ap_start = ap_const_logic_0) and (dataflow_in_loop_TILE_LOOP_1_U0_ap_idle = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(dataflow_in_loop_TILE_LOOP_1_U0_ap_ready, ap_start, loop_dataflow_input_count, bound_minus_1)
    begin
        if (((loop_dataflow_input_count = bound_minus_1) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_TILE_LOOP_1_U0_ap_ready = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound_minus_1 <= std_logic_vector(unsigned(add1) - unsigned(ap_const_lv32_1));

    dataflow_in_loop_TILE_LOOP_1_U0_ap_continue_assign_proc : process(ap_continue, loop_dataflow_output_count, bound_minus_1)
    begin
        if ((not((loop_dataflow_output_count = bound_minus_1)) or (ap_continue = ap_const_logic_1))) then 
            dataflow_in_loop_TILE_LOOP_1_U0_ap_continue <= ap_const_logic_1;
        else 
            dataflow_in_loop_TILE_LOOP_1_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    dataflow_in_loop_TILE_LOOP_1_U0_ap_start <= ap_start;
    dataflow_in_loop_TILE_LOOP_1_U0_tile_0 <= loop_dataflow_input_count(31 - 1 downto 0);
    m_axi_gmem_dw_w_0_ARADDR <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARADDR;
    m_axi_gmem_dw_w_0_ARBURST <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARBURST;
    m_axi_gmem_dw_w_0_ARCACHE <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARCACHE;
    m_axi_gmem_dw_w_0_ARID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARID;
    m_axi_gmem_dw_w_0_ARLEN <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARLEN;
    m_axi_gmem_dw_w_0_ARLOCK <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARLOCK;
    m_axi_gmem_dw_w_0_ARPROT <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARPROT;
    m_axi_gmem_dw_w_0_ARQOS <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARQOS;
    m_axi_gmem_dw_w_0_ARREGION <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARREGION;
    m_axi_gmem_dw_w_0_ARSIZE <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARSIZE;
    m_axi_gmem_dw_w_0_ARUSER <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARUSER;
    m_axi_gmem_dw_w_0_ARVALID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_ARVALID;
    m_axi_gmem_dw_w_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_dw_w_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_dw_w_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_dw_w_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_dw_w_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_dw_w_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_dw_w_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_dw_w_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_dw_w_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_dw_w_0_BREADY <= ap_const_logic_0;
    m_axi_gmem_dw_w_0_RREADY <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_dw_w_0_RREADY;
    m_axi_gmem_dw_w_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem_dw_w_0_WID <= ap_const_lv1_0;
    m_axi_gmem_dw_w_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_dw_w_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_dw_w_0_WVALID <= ap_const_logic_0;
    m_axi_gmem_in_0_ARADDR <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARADDR;
    m_axi_gmem_in_0_ARBURST <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARBURST;
    m_axi_gmem_in_0_ARCACHE <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARCACHE;
    m_axi_gmem_in_0_ARID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARID;
    m_axi_gmem_in_0_ARLEN <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARLEN;
    m_axi_gmem_in_0_ARLOCK <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARLOCK;
    m_axi_gmem_in_0_ARPROT <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARPROT;
    m_axi_gmem_in_0_ARQOS <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARQOS;
    m_axi_gmem_in_0_ARREGION <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARREGION;
    m_axi_gmem_in_0_ARSIZE <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARSIZE;
    m_axi_gmem_in_0_ARUSER <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARUSER;
    m_axi_gmem_in_0_ARVALID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_ARVALID;
    m_axi_gmem_in_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_in_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_in_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_in_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_in_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_in_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_in_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_in_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_in_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_in_0_BREADY <= ap_const_logic_0;
    m_axi_gmem_in_0_RREADY <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_in_0_RREADY;
    m_axi_gmem_in_0_WDATA <= ap_const_lv8_0;
    m_axi_gmem_in_0_WID <= ap_const_lv1_0;
    m_axi_gmem_in_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_in_0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem_in_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_in_0_WVALID <= ap_const_logic_0;
    m_axi_gmem_out_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_out_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_out_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_out_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_out_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_out_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_out_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_out_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_out_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_out_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_out_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_out_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_out_0_AWADDR <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWADDR;
    m_axi_gmem_out_0_AWBURST <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWBURST;
    m_axi_gmem_out_0_AWCACHE <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWCACHE;
    m_axi_gmem_out_0_AWID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWID;
    m_axi_gmem_out_0_AWLEN <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWLEN;
    m_axi_gmem_out_0_AWLOCK <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWLOCK;
    m_axi_gmem_out_0_AWPROT <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWPROT;
    m_axi_gmem_out_0_AWQOS <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWQOS;
    m_axi_gmem_out_0_AWREGION <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWREGION;
    m_axi_gmem_out_0_AWSIZE <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWSIZE;
    m_axi_gmem_out_0_AWUSER <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWUSER;
    m_axi_gmem_out_0_AWVALID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_AWVALID;
    m_axi_gmem_out_0_BREADY <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_BREADY;
    m_axi_gmem_out_0_RREADY <= ap_const_logic_0;
    m_axi_gmem_out_0_WDATA <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WDATA;
    m_axi_gmem_out_0_WID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WID;
    m_axi_gmem_out_0_WLAST <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WLAST;
    m_axi_gmem_out_0_WSTRB <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WSTRB;
    m_axi_gmem_out_0_WUSER <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WUSER;
    m_axi_gmem_out_0_WVALID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_out_0_WVALID;
    m_axi_gmem_pw_w_0_ARADDR <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARADDR;
    m_axi_gmem_pw_w_0_ARBURST <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARBURST;
    m_axi_gmem_pw_w_0_ARCACHE <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARCACHE;
    m_axi_gmem_pw_w_0_ARID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARID;
    m_axi_gmem_pw_w_0_ARLEN <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARLEN;
    m_axi_gmem_pw_w_0_ARLOCK <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARLOCK;
    m_axi_gmem_pw_w_0_ARPROT <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARPROT;
    m_axi_gmem_pw_w_0_ARQOS <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARQOS;
    m_axi_gmem_pw_w_0_ARREGION <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARREGION;
    m_axi_gmem_pw_w_0_ARSIZE <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARSIZE;
    m_axi_gmem_pw_w_0_ARUSER <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARUSER;
    m_axi_gmem_pw_w_0_ARVALID <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_ARVALID;
    m_axi_gmem_pw_w_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_pw_w_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_pw_w_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_pw_w_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_pw_w_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_pw_w_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_pw_w_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_pw_w_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_pw_w_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_pw_w_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_pw_w_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_pw_w_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_pw_w_0_BREADY <= ap_const_logic_0;
    m_axi_gmem_pw_w_0_RREADY <= dataflow_in_loop_TILE_LOOP_1_U0_m_axi_gmem_pw_w_0_RREADY;
    m_axi_gmem_pw_w_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem_pw_w_0_WID <= ap_const_lv1_0;
    m_axi_gmem_pw_w_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_pw_w_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_pw_w_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_pw_w_0_WVALID <= ap_const_logic_0;
end behav;
