-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mobilenet_block_accel_dw_row_stage_Pipeline_DW_LOAD_W_VITIS_LOOP_187_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_dw_w_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_dw_w_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_dw_w_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_dw_w_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_dw_w_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_dw_w_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_dw_w_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_dw_w_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_dw_w_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_dw_w_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_dw_w_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_dw_w_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_dw_w_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_dw_w_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_dw_w_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_dw_w_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    w_cache_8 : IN STD_LOGIC_VECTOR (7 downto 0);
    w_cache_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    w_cache_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    w_cache_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    w_cache_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    w_cache_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    w_cache_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    w_cache_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    w_cache : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln181_3 : IN STD_LOGIC_VECTOR (34 downto 0);
    dw_weights : IN STD_LOGIC_VECTOR (63 downto 0);
    w_cache_17_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_cache_17_out_ap_vld : OUT STD_LOGIC;
    w_cache_16_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_cache_16_out_ap_vld : OUT STD_LOGIC;
    w_cache_15_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_cache_15_out_ap_vld : OUT STD_LOGIC;
    w_cache_14_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_cache_14_out_ap_vld : OUT STD_LOGIC;
    w_cache_13_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_cache_13_out_ap_vld : OUT STD_LOGIC;
    w_cache_12_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_cache_12_out_ap_vld : OUT STD_LOGIC;
    w_cache_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_cache_11_out_ap_vld : OUT STD_LOGIC;
    w_cache_10_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_cache_10_out_ap_vld : OUT STD_LOGIC;
    w_cache_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_cache_9_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mobilenet_block_accel_dw_row_stage_Pipeline_DW_LOAD_W_VITIS_LOOP_187_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp2 : BOOLEAN;
    signal icmp_ln186_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_dw_w_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem_dw_w_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal icmp_ln186_reg_686 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln186_reg_686_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln186_reg_686_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln186_reg_686_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln186_reg_686_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln186_reg_686_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln186_reg_686_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln186_reg_686_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln186_reg_686_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln175_fu_390_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln175_reg_690_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_fu_404_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln186_reg_694_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_dw_w_addr_reg_698 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln189_fu_476_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln189_reg_704_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_dw_w_addr_read_reg_709 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp2 : BOOLEAN;
    signal sext_ln189_fu_466_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal kx_fu_110 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln187_fu_480_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_kx_load : STD_LOGIC_VECTOR (1 downto 0);
    signal ky_fu_114 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sig_allocacmp_ky_load : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten_fu_118 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln186_fu_372_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (3 downto 0);
    signal w_cache_9_fu_122 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal w_cache_18_fu_517_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal w_cache_10_fu_126 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal w_cache_11_fu_130 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal w_cache_12_fu_134 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal w_cache_13_fu_138 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal w_cache_14_fu_142 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal w_cache_15_fu_146 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal w_cache_16_fu_150 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal w_cache_17_fu_154 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal icmp_ln187_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln186_1_fu_398_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_shl_fu_416_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln186_fu_412_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln181_3_cast_fu_299_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_424_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln187_fu_430_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln189_2_fu_440_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln189_fu_446_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln189_fu_434_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln189_1_fu_450_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln189_1_fu_456_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal shl_ln3_fu_501_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln189_1_fu_508_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln189_fu_512_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_652 : BOOLEAN;
    signal ap_condition_657 : BOOLEAN;
    signal ap_condition_661 : BOOLEAN;
    signal ap_condition_664 : BOOLEAN;
    signal ap_condition_667 : BOOLEAN;
    signal ap_condition_671 : BOOLEAN;
    signal ap_condition_674 : BOOLEAN;
    signal ap_condition_679 : BOOLEAN;
    signal ap_condition_682 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component mobilenet_block_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mobilenet_block_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2)) then 
                    ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln186_fu_366_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_118 <= add_ln186_fu_372_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_118 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    kx_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln186_fu_366_p2 = ap_const_lv1_0))) then 
                    kx_fu_110 <= add_ln187_fu_480_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    kx_fu_110 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    ky_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln186_fu_366_p2 = ap_const_lv1_0))) then 
                    ky_fu_114 <= select_ln186_fu_404_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ky_fu_114 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    w_cache_10_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    w_cache_10_fu_126 <= w_cache_1;
                elsif ((ap_const_boolean_1 = ap_condition_652)) then 
                    w_cache_10_fu_126 <= w_cache_18_fu_517_p1;
                end if;
            end if; 
        end if;
    end process;

    w_cache_11_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    w_cache_11_fu_130 <= w_cache_2;
                elsif ((ap_const_boolean_1 = ap_condition_657)) then 
                    w_cache_11_fu_130 <= w_cache_18_fu_517_p1;
                end if;
            end if; 
        end if;
    end process;

    w_cache_12_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    w_cache_12_fu_134 <= w_cache_3;
                elsif ((ap_const_boolean_1 = ap_condition_661)) then 
                    w_cache_12_fu_134 <= w_cache_18_fu_517_p1;
                end if;
            end if; 
        end if;
    end process;

    w_cache_13_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    w_cache_13_fu_138 <= w_cache_4;
                elsif ((ap_const_boolean_1 = ap_condition_664)) then 
                    w_cache_13_fu_138 <= w_cache_18_fu_517_p1;
                end if;
            end if; 
        end if;
    end process;

    w_cache_14_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    w_cache_14_fu_142 <= w_cache_5;
                elsif ((ap_const_boolean_1 = ap_condition_667)) then 
                    w_cache_14_fu_142 <= w_cache_18_fu_517_p1;
                end if;
            end if; 
        end if;
    end process;

    w_cache_15_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    w_cache_15_fu_146 <= w_cache_6;
                elsif ((ap_const_boolean_1 = ap_condition_671)) then 
                    w_cache_15_fu_146 <= w_cache_18_fu_517_p1;
                end if;
            end if; 
        end if;
    end process;

    w_cache_16_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    w_cache_16_fu_150 <= w_cache_7;
                elsif ((ap_const_boolean_1 = ap_condition_674)) then 
                    w_cache_16_fu_150 <= w_cache_18_fu_517_p1;
                end if;
            end if; 
        end if;
    end process;

    w_cache_17_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    w_cache_17_fu_154 <= w_cache_8;
                elsif ((ap_const_boolean_1 = ap_condition_679)) then 
                    w_cache_17_fu_154 <= w_cache_18_fu_517_p1;
                end if;
            end if; 
        end if;
    end process;

    w_cache_9_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    w_cache_9_fu_122 <= w_cache;
                elsif ((ap_const_boolean_1 = ap_condition_682)) then 
                    w_cache_9_fu_122 <= w_cache_18_fu_517_p1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                gmem_dw_w_addr_reg_698 <= sext_ln189_fu_466_p1;
                icmp_ln186_reg_686 <= icmp_ln186_fu_366_p2;
                icmp_ln186_reg_686_pp0_iter1_reg <= icmp_ln186_reg_686;
                select_ln175_reg_690 <= select_ln175_fu_390_p3;
                select_ln175_reg_690_pp0_iter1_reg <= select_ln175_reg_690;
                select_ln186_reg_694 <= select_ln186_fu_404_p3;
                select_ln186_reg_694_pp0_iter1_reg <= select_ln186_reg_694;
                trunc_ln189_reg_704 <= trunc_ln189_fu_476_p1;
                trunc_ln189_reg_704_pp0_iter1_reg <= trunc_ln189_reg_704;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln186_reg_686_pp0_iter2_reg <= icmp_ln186_reg_686_pp0_iter1_reg;
                icmp_ln186_reg_686_pp0_iter3_reg <= icmp_ln186_reg_686_pp0_iter2_reg;
                icmp_ln186_reg_686_pp0_iter4_reg <= icmp_ln186_reg_686_pp0_iter3_reg;
                icmp_ln186_reg_686_pp0_iter5_reg <= icmp_ln186_reg_686_pp0_iter4_reg;
                icmp_ln186_reg_686_pp0_iter6_reg <= icmp_ln186_reg_686_pp0_iter5_reg;
                icmp_ln186_reg_686_pp0_iter7_reg <= icmp_ln186_reg_686_pp0_iter6_reg;
                icmp_ln186_reg_686_pp0_iter8_reg <= icmp_ln186_reg_686_pp0_iter7_reg;
                select_ln175_reg_690_pp0_iter2_reg <= select_ln175_reg_690_pp0_iter1_reg;
                select_ln175_reg_690_pp0_iter3_reg <= select_ln175_reg_690_pp0_iter2_reg;
                select_ln175_reg_690_pp0_iter4_reg <= select_ln175_reg_690_pp0_iter3_reg;
                select_ln175_reg_690_pp0_iter5_reg <= select_ln175_reg_690_pp0_iter4_reg;
                select_ln175_reg_690_pp0_iter6_reg <= select_ln175_reg_690_pp0_iter5_reg;
                select_ln175_reg_690_pp0_iter7_reg <= select_ln175_reg_690_pp0_iter6_reg;
                select_ln175_reg_690_pp0_iter8_reg <= select_ln175_reg_690_pp0_iter7_reg;
                select_ln175_reg_690_pp0_iter9_reg <= select_ln175_reg_690_pp0_iter8_reg;
                select_ln186_reg_694_pp0_iter2_reg <= select_ln186_reg_694_pp0_iter1_reg;
                select_ln186_reg_694_pp0_iter3_reg <= select_ln186_reg_694_pp0_iter2_reg;
                select_ln186_reg_694_pp0_iter4_reg <= select_ln186_reg_694_pp0_iter3_reg;
                select_ln186_reg_694_pp0_iter5_reg <= select_ln186_reg_694_pp0_iter4_reg;
                select_ln186_reg_694_pp0_iter6_reg <= select_ln186_reg_694_pp0_iter5_reg;
                select_ln186_reg_694_pp0_iter7_reg <= select_ln186_reg_694_pp0_iter6_reg;
                select_ln186_reg_694_pp0_iter8_reg <= select_ln186_reg_694_pp0_iter7_reg;
                select_ln186_reg_694_pp0_iter9_reg <= select_ln186_reg_694_pp0_iter8_reg;
                trunc_ln189_reg_704_pp0_iter2_reg <= trunc_ln189_reg_704_pp0_iter1_reg;
                trunc_ln189_reg_704_pp0_iter3_reg <= trunc_ln189_reg_704_pp0_iter2_reg;
                trunc_ln189_reg_704_pp0_iter4_reg <= trunc_ln189_reg_704_pp0_iter3_reg;
                trunc_ln189_reg_704_pp0_iter5_reg <= trunc_ln189_reg_704_pp0_iter4_reg;
                trunc_ln189_reg_704_pp0_iter6_reg <= trunc_ln189_reg_704_pp0_iter5_reg;
                trunc_ln189_reg_704_pp0_iter7_reg <= trunc_ln189_reg_704_pp0_iter6_reg;
                trunc_ln189_reg_704_pp0_iter8_reg <= trunc_ln189_reg_704_pp0_iter7_reg;
                trunc_ln189_reg_704_pp0_iter9_reg <= trunc_ln189_reg_704_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg))) then
                gmem_dw_w_addr_read_reg_709 <= m_axi_gmem_dw_w_0_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln186_1_fu_398_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ky_load) + unsigned(ap_const_lv2_1));
    add_ln186_fu_372_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv4_1));
    add_ln187_fu_480_p2 <= std_logic_vector(unsigned(select_ln175_fu_390_p3) + unsigned(ap_const_lv2_1));
    add_ln189_1_fu_450_p2 <= std_logic_vector(unsigned(zext_ln189_fu_446_p1) + unsigned(add_ln189_fu_434_p2));
    add_ln189_2_fu_440_p2 <= std_logic_vector(unsigned(empty_fu_424_p2) + unsigned(zext_ln187_fu_430_p1));
    add_ln189_fu_434_p2 <= std_logic_vector(unsigned(zext_ln181_3_cast_fu_299_p1) + unsigned(dw_weights));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, m_axi_gmem_dw_w_0_ARREADY, m_axi_gmem_dw_w_0_RVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_gmem_dw_w_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((m_axi_gmem_dw_w_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_dw_w_0_ARREADY, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem_dw_w_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem_dw_w_0_RVALID, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp2 <= ((m_axi_gmem_dw_w_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, m_axi_gmem_dw_w_0_ARREADY, m_axi_gmem_dw_w_0_RVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_gmem_dw_w_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((m_axi_gmem_dw_w_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_dw_w_0_ARREADY, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((m_axi_gmem_dw_w_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem_dw_w_0_RVALID, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp2 <= ((m_axi_gmem_dw_w_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg));
    end process;


    ap_condition_652_assign_proc : process(ap_enable_reg_pp0_iter10, select_ln175_reg_690_pp0_iter9_reg, select_ln186_reg_694_pp0_iter9_reg)
    begin
                ap_condition_652 <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_0) and (select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_1));
    end process;


    ap_condition_657_assign_proc : process(ap_enable_reg_pp0_iter10, select_ln175_reg_690_pp0_iter9_reg, select_ln186_reg_694_pp0_iter9_reg)
    begin
                ap_condition_657 <= (not((select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_1)) and not((select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_0));
    end process;


    ap_condition_661_assign_proc : process(ap_enable_reg_pp0_iter10, select_ln175_reg_690_pp0_iter9_reg, select_ln186_reg_694_pp0_iter9_reg)
    begin
                ap_condition_661 <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_1) and (select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_0));
    end process;


    ap_condition_664_assign_proc : process(ap_enable_reg_pp0_iter10, select_ln175_reg_690_pp0_iter9_reg, select_ln186_reg_694_pp0_iter9_reg)
    begin
                ap_condition_664 <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_1) and (select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_1));
    end process;


    ap_condition_667_assign_proc : process(ap_enable_reg_pp0_iter10, select_ln175_reg_690_pp0_iter9_reg, select_ln186_reg_694_pp0_iter9_reg)
    begin
                ap_condition_667 <= (not((select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_1)) and not((select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_1));
    end process;


    ap_condition_671_assign_proc : process(ap_enable_reg_pp0_iter10, select_ln175_reg_690_pp0_iter9_reg, select_ln186_reg_694_pp0_iter9_reg)
    begin
                ap_condition_671 <= (not((select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_1)) and not((select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_0));
    end process;


    ap_condition_674_assign_proc : process(ap_enable_reg_pp0_iter10, select_ln175_reg_690_pp0_iter9_reg, select_ln186_reg_694_pp0_iter9_reg)
    begin
                ap_condition_674 <= (not((select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_1)) and not((select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_1));
    end process;


    ap_condition_679_assign_proc : process(ap_enable_reg_pp0_iter10, select_ln175_reg_690_pp0_iter9_reg, select_ln186_reg_694_pp0_iter9_reg)
    begin
                ap_condition_679 <= (not((select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_1)) and not((select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_1)) and not((select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_0)) and not((select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1));
    end process;


    ap_condition_682_assign_proc : process(ap_enable_reg_pp0_iter10, select_ln175_reg_690_pp0_iter9_reg, select_ln186_reg_694_pp0_iter9_reg)
    begin
                ap_condition_682 <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (select_ln186_reg_694_pp0_iter9_reg = ap_const_lv2_0) and (select_ln175_reg_690_pp0_iter9_reg = ap_const_lv2_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln186_fu_366_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln186_fu_366_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter9_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_118)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_118;
        end if; 
    end process;


    ap_sig_allocacmp_kx_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, kx_fu_110, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_kx_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_kx_load <= kx_fu_110;
        end if; 
    end process;


    ap_sig_allocacmp_ky_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ky_fu_114)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_ky_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_ky_load <= ky_fu_114;
        end if; 
    end process;

    empty_fu_424_p2 <= std_logic_vector(unsigned(p_shl_fu_416_p3) - unsigned(zext_ln186_fu_412_p1));

    gmem_dw_w_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_dw_w_0_ARREADY, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg))) then 
            gmem_dw_w_blk_n_AR <= m_axi_gmem_dw_w_0_ARREADY;
        else 
            gmem_dw_w_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_dw_w_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem_dw_w_0_RVALID, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_grp2)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg))) then 
            gmem_dw_w_blk_n_R <= m_axi_gmem_dw_w_0_RVALID;
        else 
            gmem_dw_w_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln186_fu_366_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv4_9) else "0";
    icmp_ln187_fu_384_p2 <= "1" when (ap_sig_allocacmp_kx_load = ap_const_lv2_3) else "0";
    lshr_ln189_fu_512_p2 <= std_logic_vector(shift_right(unsigned(gmem_dw_w_addr_read_reg_709),to_integer(unsigned('0' & zext_ln189_1_fu_508_p1(31-1 downto 0)))));
    m_axi_gmem_dw_w_0_ARADDR <= gmem_dw_w_addr_reg_698;
    m_axi_gmem_dw_w_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_dw_w_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_dw_w_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem_dw_w_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_dw_w_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_dw_w_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_dw_w_0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_dw_w_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg))) then 
            m_axi_gmem_dw_w_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_dw_w_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_dw_w_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_dw_w_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_dw_w_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_dw_w_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_dw_w_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_dw_w_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_dw_w_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_dw_w_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_dw_w_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_dw_w_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_dw_w_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg))) then 
            m_axi_gmem_dw_w_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_dw_w_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_dw_w_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem_dw_w_0_WID <= ap_const_lv1_0;
    m_axi_gmem_dw_w_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_dw_w_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_dw_w_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_dw_w_0_WVALID <= ap_const_logic_0;
    p_shl_fu_416_p3 <= (select_ln186_fu_404_p3 & ap_const_lv2_0);
    select_ln175_fu_390_p3 <= 
        ap_const_lv2_0 when (icmp_ln187_fu_384_p2(0) = '1') else 
        ap_sig_allocacmp_kx_load;
    select_ln186_fu_404_p3 <= 
        add_ln186_1_fu_398_p2 when (icmp_ln187_fu_384_p2(0) = '1') else 
        ap_sig_allocacmp_ky_load;
        sext_ln189_fu_466_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln189_1_fu_456_p4),64));

    shl_ln3_fu_501_p3 <= (trunc_ln189_reg_704_pp0_iter9_reg & ap_const_lv3_0);
    trunc_ln189_1_fu_456_p4 <= add_ln189_1_fu_450_p2(63 downto 2);
    trunc_ln189_fu_476_p1 <= add_ln189_1_fu_450_p2(2 - 1 downto 0);
    w_cache_10_out <= w_cache_10_fu_126;

    w_cache_10_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln186_reg_686_pp0_iter8_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (icmp_ln186_reg_686_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            w_cache_10_out_ap_vld <= ap_const_logic_1;
        else 
            w_cache_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_cache_11_out <= w_cache_11_fu_130;

    w_cache_11_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln186_reg_686_pp0_iter8_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (icmp_ln186_reg_686_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            w_cache_11_out_ap_vld <= ap_const_logic_1;
        else 
            w_cache_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_cache_12_out <= w_cache_12_fu_134;

    w_cache_12_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln186_reg_686_pp0_iter8_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (icmp_ln186_reg_686_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            w_cache_12_out_ap_vld <= ap_const_logic_1;
        else 
            w_cache_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_cache_13_out <= w_cache_13_fu_138;

    w_cache_13_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln186_reg_686_pp0_iter8_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (icmp_ln186_reg_686_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            w_cache_13_out_ap_vld <= ap_const_logic_1;
        else 
            w_cache_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_cache_14_out <= w_cache_14_fu_142;

    w_cache_14_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln186_reg_686_pp0_iter8_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (icmp_ln186_reg_686_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            w_cache_14_out_ap_vld <= ap_const_logic_1;
        else 
            w_cache_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_cache_15_out <= w_cache_15_fu_146;

    w_cache_15_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln186_reg_686_pp0_iter8_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (icmp_ln186_reg_686_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            w_cache_15_out_ap_vld <= ap_const_logic_1;
        else 
            w_cache_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_cache_16_out <= w_cache_16_fu_150;

    w_cache_16_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln186_reg_686_pp0_iter8_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (icmp_ln186_reg_686_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            w_cache_16_out_ap_vld <= ap_const_logic_1;
        else 
            w_cache_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_cache_17_out <= w_cache_17_fu_154;

    w_cache_17_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln186_reg_686_pp0_iter8_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (icmp_ln186_reg_686_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            w_cache_17_out_ap_vld <= ap_const_logic_1;
        else 
            w_cache_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_cache_18_fu_517_p1 <= lshr_ln189_fu_512_p2(8 - 1 downto 0);
    w_cache_9_out <= w_cache_9_fu_122;

    w_cache_9_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln186_reg_686_pp0_iter8_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (icmp_ln186_reg_686_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            w_cache_9_out_ap_vld <= ap_const_logic_1;
        else 
            w_cache_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln181_3_cast_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln181_3),64));
    zext_ln186_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln186_fu_404_p3),4));
    zext_ln187_fu_430_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln175_fu_390_p3),4));
    zext_ln189_1_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln3_fu_501_p3),32));
    zext_ln189_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln189_2_fu_440_p2),64));
end behav;
