// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenet_block_accel_dataflow_in_loop_TILE_LOOP_1_Block_if_end_aft_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        m_axi_gmem_pw_w_0_AWVALID,
        m_axi_gmem_pw_w_0_AWREADY,
        m_axi_gmem_pw_w_0_AWADDR,
        m_axi_gmem_pw_w_0_AWID,
        m_axi_gmem_pw_w_0_AWLEN,
        m_axi_gmem_pw_w_0_AWSIZE,
        m_axi_gmem_pw_w_0_AWBURST,
        m_axi_gmem_pw_w_0_AWLOCK,
        m_axi_gmem_pw_w_0_AWCACHE,
        m_axi_gmem_pw_w_0_AWPROT,
        m_axi_gmem_pw_w_0_AWQOS,
        m_axi_gmem_pw_w_0_AWREGION,
        m_axi_gmem_pw_w_0_AWUSER,
        m_axi_gmem_pw_w_0_WVALID,
        m_axi_gmem_pw_w_0_WREADY,
        m_axi_gmem_pw_w_0_WDATA,
        m_axi_gmem_pw_w_0_WSTRB,
        m_axi_gmem_pw_w_0_WLAST,
        m_axi_gmem_pw_w_0_WID,
        m_axi_gmem_pw_w_0_WUSER,
        m_axi_gmem_pw_w_0_ARVALID,
        m_axi_gmem_pw_w_0_ARREADY,
        m_axi_gmem_pw_w_0_ARADDR,
        m_axi_gmem_pw_w_0_ARID,
        m_axi_gmem_pw_w_0_ARLEN,
        m_axi_gmem_pw_w_0_ARSIZE,
        m_axi_gmem_pw_w_0_ARBURST,
        m_axi_gmem_pw_w_0_ARLOCK,
        m_axi_gmem_pw_w_0_ARCACHE,
        m_axi_gmem_pw_w_0_ARPROT,
        m_axi_gmem_pw_w_0_ARQOS,
        m_axi_gmem_pw_w_0_ARREGION,
        m_axi_gmem_pw_w_0_ARUSER,
        m_axi_gmem_pw_w_0_RVALID,
        m_axi_gmem_pw_w_0_RREADY,
        m_axi_gmem_pw_w_0_RDATA,
        m_axi_gmem_pw_w_0_RLAST,
        m_axi_gmem_pw_w_0_RID,
        m_axi_gmem_pw_w_0_RFIFONUM,
        m_axi_gmem_pw_w_0_RUSER,
        m_axi_gmem_pw_w_0_RRESP,
        m_axi_gmem_pw_w_0_BVALID,
        m_axi_gmem_pw_w_0_BREADY,
        m_axi_gmem_pw_w_0_BRESP,
        m_axi_gmem_pw_w_0_BID,
        m_axi_gmem_pw_w_0_BUSER,
        pw_weights,
        pw_bias,
        m_axi_gmem_out_0_AWVALID,
        m_axi_gmem_out_0_AWREADY,
        m_axi_gmem_out_0_AWADDR,
        m_axi_gmem_out_0_AWID,
        m_axi_gmem_out_0_AWLEN,
        m_axi_gmem_out_0_AWSIZE,
        m_axi_gmem_out_0_AWBURST,
        m_axi_gmem_out_0_AWLOCK,
        m_axi_gmem_out_0_AWCACHE,
        m_axi_gmem_out_0_AWPROT,
        m_axi_gmem_out_0_AWQOS,
        m_axi_gmem_out_0_AWREGION,
        m_axi_gmem_out_0_AWUSER,
        m_axi_gmem_out_0_WVALID,
        m_axi_gmem_out_0_WREADY,
        m_axi_gmem_out_0_WDATA,
        m_axi_gmem_out_0_WSTRB,
        m_axi_gmem_out_0_WLAST,
        m_axi_gmem_out_0_WID,
        m_axi_gmem_out_0_WUSER,
        m_axi_gmem_out_0_ARVALID,
        m_axi_gmem_out_0_ARREADY,
        m_axi_gmem_out_0_ARADDR,
        m_axi_gmem_out_0_ARID,
        m_axi_gmem_out_0_ARLEN,
        m_axi_gmem_out_0_ARSIZE,
        m_axi_gmem_out_0_ARBURST,
        m_axi_gmem_out_0_ARLOCK,
        m_axi_gmem_out_0_ARCACHE,
        m_axi_gmem_out_0_ARPROT,
        m_axi_gmem_out_0_ARQOS,
        m_axi_gmem_out_0_ARREGION,
        m_axi_gmem_out_0_ARUSER,
        m_axi_gmem_out_0_RVALID,
        m_axi_gmem_out_0_RREADY,
        m_axi_gmem_out_0_RDATA,
        m_axi_gmem_out_0_RLAST,
        m_axi_gmem_out_0_RID,
        m_axi_gmem_out_0_RFIFONUM,
        m_axi_gmem_out_0_RUSER,
        m_axi_gmem_out_0_RRESP,
        m_axi_gmem_out_0_BVALID,
        m_axi_gmem_out_0_BREADY,
        m_axi_gmem_out_0_BRESP,
        m_axi_gmem_out_0_BID,
        m_axi_gmem_out_0_BUSER,
        output_r,
        p_read2,
        height,
        width,
        c_in,
        c_out,
        pw_act_zp,
        pw_wgt_zp,
        pw_out_zp,
        pw_M_mantissa,
        pw_M_shift,
        pw_use_bias,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_q0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_address0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_ce0,
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_q0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_address0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_ce0,
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_q0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] p_read;
input  [0:0] p_read1;
output   m_axi_gmem_pw_w_0_AWVALID;
input   m_axi_gmem_pw_w_0_AWREADY;
output  [63:0] m_axi_gmem_pw_w_0_AWADDR;
output  [0:0] m_axi_gmem_pw_w_0_AWID;
output  [31:0] m_axi_gmem_pw_w_0_AWLEN;
output  [2:0] m_axi_gmem_pw_w_0_AWSIZE;
output  [1:0] m_axi_gmem_pw_w_0_AWBURST;
output  [1:0] m_axi_gmem_pw_w_0_AWLOCK;
output  [3:0] m_axi_gmem_pw_w_0_AWCACHE;
output  [2:0] m_axi_gmem_pw_w_0_AWPROT;
output  [3:0] m_axi_gmem_pw_w_0_AWQOS;
output  [3:0] m_axi_gmem_pw_w_0_AWREGION;
output  [0:0] m_axi_gmem_pw_w_0_AWUSER;
output   m_axi_gmem_pw_w_0_WVALID;
input   m_axi_gmem_pw_w_0_WREADY;
output  [31:0] m_axi_gmem_pw_w_0_WDATA;
output  [3:0] m_axi_gmem_pw_w_0_WSTRB;
output   m_axi_gmem_pw_w_0_WLAST;
output  [0:0] m_axi_gmem_pw_w_0_WID;
output  [0:0] m_axi_gmem_pw_w_0_WUSER;
output   m_axi_gmem_pw_w_0_ARVALID;
input   m_axi_gmem_pw_w_0_ARREADY;
output  [63:0] m_axi_gmem_pw_w_0_ARADDR;
output  [0:0] m_axi_gmem_pw_w_0_ARID;
output  [31:0] m_axi_gmem_pw_w_0_ARLEN;
output  [2:0] m_axi_gmem_pw_w_0_ARSIZE;
output  [1:0] m_axi_gmem_pw_w_0_ARBURST;
output  [1:0] m_axi_gmem_pw_w_0_ARLOCK;
output  [3:0] m_axi_gmem_pw_w_0_ARCACHE;
output  [2:0] m_axi_gmem_pw_w_0_ARPROT;
output  [3:0] m_axi_gmem_pw_w_0_ARQOS;
output  [3:0] m_axi_gmem_pw_w_0_ARREGION;
output  [0:0] m_axi_gmem_pw_w_0_ARUSER;
input   m_axi_gmem_pw_w_0_RVALID;
output   m_axi_gmem_pw_w_0_RREADY;
input  [31:0] m_axi_gmem_pw_w_0_RDATA;
input   m_axi_gmem_pw_w_0_RLAST;
input  [0:0] m_axi_gmem_pw_w_0_RID;
input  [8:0] m_axi_gmem_pw_w_0_RFIFONUM;
input  [0:0] m_axi_gmem_pw_w_0_RUSER;
input  [1:0] m_axi_gmem_pw_w_0_RRESP;
input   m_axi_gmem_pw_w_0_BVALID;
output   m_axi_gmem_pw_w_0_BREADY;
input  [1:0] m_axi_gmem_pw_w_0_BRESP;
input  [0:0] m_axi_gmem_pw_w_0_BID;
input  [0:0] m_axi_gmem_pw_w_0_BUSER;
input  [63:0] pw_weights;
input  [63:0] pw_bias;
output   m_axi_gmem_out_0_AWVALID;
input   m_axi_gmem_out_0_AWREADY;
output  [63:0] m_axi_gmem_out_0_AWADDR;
output  [0:0] m_axi_gmem_out_0_AWID;
output  [31:0] m_axi_gmem_out_0_AWLEN;
output  [2:0] m_axi_gmem_out_0_AWSIZE;
output  [1:0] m_axi_gmem_out_0_AWBURST;
output  [1:0] m_axi_gmem_out_0_AWLOCK;
output  [3:0] m_axi_gmem_out_0_AWCACHE;
output  [2:0] m_axi_gmem_out_0_AWPROT;
output  [3:0] m_axi_gmem_out_0_AWQOS;
output  [3:0] m_axi_gmem_out_0_AWREGION;
output  [0:0] m_axi_gmem_out_0_AWUSER;
output   m_axi_gmem_out_0_WVALID;
input   m_axi_gmem_out_0_WREADY;
output  [7:0] m_axi_gmem_out_0_WDATA;
output  [0:0] m_axi_gmem_out_0_WSTRB;
output   m_axi_gmem_out_0_WLAST;
output  [0:0] m_axi_gmem_out_0_WID;
output  [0:0] m_axi_gmem_out_0_WUSER;
output   m_axi_gmem_out_0_ARVALID;
input   m_axi_gmem_out_0_ARREADY;
output  [63:0] m_axi_gmem_out_0_ARADDR;
output  [0:0] m_axi_gmem_out_0_ARID;
output  [31:0] m_axi_gmem_out_0_ARLEN;
output  [2:0] m_axi_gmem_out_0_ARSIZE;
output  [1:0] m_axi_gmem_out_0_ARBURST;
output  [1:0] m_axi_gmem_out_0_ARLOCK;
output  [3:0] m_axi_gmem_out_0_ARCACHE;
output  [2:0] m_axi_gmem_out_0_ARPROT;
output  [3:0] m_axi_gmem_out_0_ARQOS;
output  [3:0] m_axi_gmem_out_0_ARREGION;
output  [0:0] m_axi_gmem_out_0_ARUSER;
input   m_axi_gmem_out_0_RVALID;
output   m_axi_gmem_out_0_RREADY;
input  [7:0] m_axi_gmem_out_0_RDATA;
input   m_axi_gmem_out_0_RLAST;
input  [0:0] m_axi_gmem_out_0_RID;
input  [10:0] m_axi_gmem_out_0_RFIFONUM;
input  [0:0] m_axi_gmem_out_0_RUSER;
input  [1:0] m_axi_gmem_out_0_RRESP;
input   m_axi_gmem_out_0_BVALID;
output   m_axi_gmem_out_0_BREADY;
input  [1:0] m_axi_gmem_out_0_BRESP;
input  [0:0] m_axi_gmem_out_0_BID;
input  [0:0] m_axi_gmem_out_0_BUSER;
input  [63:0] output_r;
input  [31:0] p_read2;
input  [31:0] height;
input  [31:0] width;
input  [31:0] c_in;
input  [31:0] c_out;
input  [15:0] pw_act_zp;
input  [15:0] pw_wgt_zp;
input  [31:0] pw_out_zp;
input  [31:0] pw_M_mantissa;
input  [31:0] pw_M_shift;
input  [31:0] pw_use_bias;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_q0;
output  [12:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_address0;
output   mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_ce0;
input  [7:0] mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_q0;
output  [12:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_address0;
output   p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_ce0;
input  [7:0] p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_pw_w_0_ARVALID;
reg m_axi_gmem_pw_w_0_RREADY;
reg m_axi_gmem_out_0_AWVALID;
reg m_axi_gmem_out_0_WVALID;
reg m_axi_gmem_out_0_BREADY;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_ce0;
reg mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_ce0;
reg p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_ce0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] pw_use_bias_read_reg_312;
reg    ap_block_state1;
reg   [31:0] pw_M_shift_read_reg_317;
reg   [31:0] pw_M_mantissa_read_reg_322;
reg   [31:0] pw_out_zp_read_reg_327;
reg   [15:0] pw_wgt_zp_read_reg_332;
reg   [15:0] pw_act_zp_read_reg_337;
reg   [31:0] c_out_read_reg_342;
reg   [31:0] c_in_read_reg_347;
reg   [31:0] width_read_reg_352;
reg   [31:0] height_read_reg_357;
reg   [31:0] p_read_2_reg_362;
reg   [63:0] output_read_reg_367;
reg   [63:0] pw_bias_read_reg_372;
reg   [63:0] pw_weights_read_reg_377;
wire   [0:0] p_read_3_read_fu_216_p2;
reg   [0:0] p_read_3_reg_382;
wire   [0:0] p_read_4_read_fu_222_p2;
reg   [0:0] p_read_4_reg_386;
wire    grp_pw_row_stage_fu_228_ap_start;
wire    grp_pw_row_stage_fu_228_ap_done;
wire    grp_pw_row_stage_fu_228_ap_idle;
wire    grp_pw_row_stage_fu_228_ap_ready;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_0_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_0_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_0_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_1_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_1_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_1_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_2_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_2_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_2_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_3_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_3_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_3_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_4_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_4_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_4_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_5_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_5_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_5_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_6_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_6_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_6_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_7_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_7_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_7_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_8_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_8_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_8_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_9_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_9_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_9_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_10_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_10_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_10_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_11_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_11_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_11_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_12_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_12_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_12_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_13_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_13_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_13_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_14_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_14_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_14_q0;
wire   [12:0] grp_pw_row_stage_fu_228_inter_buf_15_address0;
wire    grp_pw_row_stage_fu_228_inter_buf_15_ce0;
reg   [7:0] grp_pw_row_stage_fu_228_inter_buf_15_q0;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWVALID;
wire   [63:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWADDR;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWID;
wire   [31:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWLEN;
wire   [2:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWSIZE;
wire   [1:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWBURST;
wire   [1:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWLOCK;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWCACHE;
wire   [2:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWPROT;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWQOS;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWREGION;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWUSER;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WVALID;
wire   [31:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WDATA;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WSTRB;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WLAST;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WID;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WUSER;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARVALID;
wire   [63:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARADDR;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARID;
wire   [31:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARLEN;
wire   [2:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARSIZE;
wire   [1:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARBURST;
wire   [1:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARLOCK;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARCACHE;
wire   [2:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARPROT;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARQOS;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARREGION;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARUSER;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_RREADY;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_BREADY;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWVALID;
wire   [63:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWADDR;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWID;
wire   [31:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWLEN;
wire   [2:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWSIZE;
wire   [1:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWBURST;
wire   [1:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWLOCK;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWCACHE;
wire   [2:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWPROT;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWQOS;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWREGION;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWUSER;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WVALID;
wire   [7:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WDATA;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WSTRB;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WLAST;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WID;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WUSER;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARVALID;
wire   [63:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARADDR;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARID;
wire   [31:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARLEN;
wire   [2:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARSIZE;
wire   [1:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARBURST;
wire   [1:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARLOCK;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARCACHE;
wire   [2:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARPROT;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARQOS;
wire   [3:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARREGION;
wire   [0:0] grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARUSER;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_out_0_RREADY;
wire    grp_pw_row_stage_fu_228_m_axi_gmem_out_0_BREADY;
reg    grp_pw_row_stage_fu_228_ap_start_reg;
reg    ap_block_state1_ignore_call0;
wire    ap_CS_fsm_state2;
reg    ap_predicate_op25_call_state2;
reg    ap_predicate_op27_call_state2;
reg    ap_block_state2_on_subcall_done;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_pw_row_stage_fu_228_ap_start_reg = 1'b0;
end

mobilenet_block_accel_pw_row_stage grp_pw_row_stage_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pw_row_stage_fu_228_ap_start),
    .ap_done(grp_pw_row_stage_fu_228_ap_done),
    .ap_idle(grp_pw_row_stage_fu_228_ap_idle),
    .ap_ready(grp_pw_row_stage_fu_228_ap_ready),
    .inter_buf_0_address0(grp_pw_row_stage_fu_228_inter_buf_0_address0),
    .inter_buf_0_ce0(grp_pw_row_stage_fu_228_inter_buf_0_ce0),
    .inter_buf_0_q0(grp_pw_row_stage_fu_228_inter_buf_0_q0),
    .inter_buf_1_address0(grp_pw_row_stage_fu_228_inter_buf_1_address0),
    .inter_buf_1_ce0(grp_pw_row_stage_fu_228_inter_buf_1_ce0),
    .inter_buf_1_q0(grp_pw_row_stage_fu_228_inter_buf_1_q0),
    .inter_buf_2_address0(grp_pw_row_stage_fu_228_inter_buf_2_address0),
    .inter_buf_2_ce0(grp_pw_row_stage_fu_228_inter_buf_2_ce0),
    .inter_buf_2_q0(grp_pw_row_stage_fu_228_inter_buf_2_q0),
    .inter_buf_3_address0(grp_pw_row_stage_fu_228_inter_buf_3_address0),
    .inter_buf_3_ce0(grp_pw_row_stage_fu_228_inter_buf_3_ce0),
    .inter_buf_3_q0(grp_pw_row_stage_fu_228_inter_buf_3_q0),
    .inter_buf_4_address0(grp_pw_row_stage_fu_228_inter_buf_4_address0),
    .inter_buf_4_ce0(grp_pw_row_stage_fu_228_inter_buf_4_ce0),
    .inter_buf_4_q0(grp_pw_row_stage_fu_228_inter_buf_4_q0),
    .inter_buf_5_address0(grp_pw_row_stage_fu_228_inter_buf_5_address0),
    .inter_buf_5_ce0(grp_pw_row_stage_fu_228_inter_buf_5_ce0),
    .inter_buf_5_q0(grp_pw_row_stage_fu_228_inter_buf_5_q0),
    .inter_buf_6_address0(grp_pw_row_stage_fu_228_inter_buf_6_address0),
    .inter_buf_6_ce0(grp_pw_row_stage_fu_228_inter_buf_6_ce0),
    .inter_buf_6_q0(grp_pw_row_stage_fu_228_inter_buf_6_q0),
    .inter_buf_7_address0(grp_pw_row_stage_fu_228_inter_buf_7_address0),
    .inter_buf_7_ce0(grp_pw_row_stage_fu_228_inter_buf_7_ce0),
    .inter_buf_7_q0(grp_pw_row_stage_fu_228_inter_buf_7_q0),
    .inter_buf_8_address0(grp_pw_row_stage_fu_228_inter_buf_8_address0),
    .inter_buf_8_ce0(grp_pw_row_stage_fu_228_inter_buf_8_ce0),
    .inter_buf_8_q0(grp_pw_row_stage_fu_228_inter_buf_8_q0),
    .inter_buf_9_address0(grp_pw_row_stage_fu_228_inter_buf_9_address0),
    .inter_buf_9_ce0(grp_pw_row_stage_fu_228_inter_buf_9_ce0),
    .inter_buf_9_q0(grp_pw_row_stage_fu_228_inter_buf_9_q0),
    .inter_buf_10_address0(grp_pw_row_stage_fu_228_inter_buf_10_address0),
    .inter_buf_10_ce0(grp_pw_row_stage_fu_228_inter_buf_10_ce0),
    .inter_buf_10_q0(grp_pw_row_stage_fu_228_inter_buf_10_q0),
    .inter_buf_11_address0(grp_pw_row_stage_fu_228_inter_buf_11_address0),
    .inter_buf_11_ce0(grp_pw_row_stage_fu_228_inter_buf_11_ce0),
    .inter_buf_11_q0(grp_pw_row_stage_fu_228_inter_buf_11_q0),
    .inter_buf_12_address0(grp_pw_row_stage_fu_228_inter_buf_12_address0),
    .inter_buf_12_ce0(grp_pw_row_stage_fu_228_inter_buf_12_ce0),
    .inter_buf_12_q0(grp_pw_row_stage_fu_228_inter_buf_12_q0),
    .inter_buf_13_address0(grp_pw_row_stage_fu_228_inter_buf_13_address0),
    .inter_buf_13_ce0(grp_pw_row_stage_fu_228_inter_buf_13_ce0),
    .inter_buf_13_q0(grp_pw_row_stage_fu_228_inter_buf_13_q0),
    .inter_buf_14_address0(grp_pw_row_stage_fu_228_inter_buf_14_address0),
    .inter_buf_14_ce0(grp_pw_row_stage_fu_228_inter_buf_14_ce0),
    .inter_buf_14_q0(grp_pw_row_stage_fu_228_inter_buf_14_q0),
    .inter_buf_15_address0(grp_pw_row_stage_fu_228_inter_buf_15_address0),
    .inter_buf_15_ce0(grp_pw_row_stage_fu_228_inter_buf_15_ce0),
    .inter_buf_15_q0(grp_pw_row_stage_fu_228_inter_buf_15_q0),
    .m_axi_gmem_pw_w_0_AWVALID(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWVALID),
    .m_axi_gmem_pw_w_0_AWREADY(1'b0),
    .m_axi_gmem_pw_w_0_AWADDR(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWADDR),
    .m_axi_gmem_pw_w_0_AWID(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWID),
    .m_axi_gmem_pw_w_0_AWLEN(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWLEN),
    .m_axi_gmem_pw_w_0_AWSIZE(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWSIZE),
    .m_axi_gmem_pw_w_0_AWBURST(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWBURST),
    .m_axi_gmem_pw_w_0_AWLOCK(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWLOCK),
    .m_axi_gmem_pw_w_0_AWCACHE(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWCACHE),
    .m_axi_gmem_pw_w_0_AWPROT(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWPROT),
    .m_axi_gmem_pw_w_0_AWQOS(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWQOS),
    .m_axi_gmem_pw_w_0_AWREGION(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWREGION),
    .m_axi_gmem_pw_w_0_AWUSER(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_AWUSER),
    .m_axi_gmem_pw_w_0_WVALID(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WVALID),
    .m_axi_gmem_pw_w_0_WREADY(1'b0),
    .m_axi_gmem_pw_w_0_WDATA(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WDATA),
    .m_axi_gmem_pw_w_0_WSTRB(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WSTRB),
    .m_axi_gmem_pw_w_0_WLAST(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WLAST),
    .m_axi_gmem_pw_w_0_WID(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WID),
    .m_axi_gmem_pw_w_0_WUSER(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_WUSER),
    .m_axi_gmem_pw_w_0_ARVALID(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARVALID),
    .m_axi_gmem_pw_w_0_ARREADY(m_axi_gmem_pw_w_0_ARREADY),
    .m_axi_gmem_pw_w_0_ARADDR(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARADDR),
    .m_axi_gmem_pw_w_0_ARID(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARID),
    .m_axi_gmem_pw_w_0_ARLEN(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARLEN),
    .m_axi_gmem_pw_w_0_ARSIZE(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARSIZE),
    .m_axi_gmem_pw_w_0_ARBURST(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARBURST),
    .m_axi_gmem_pw_w_0_ARLOCK(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARLOCK),
    .m_axi_gmem_pw_w_0_ARCACHE(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARCACHE),
    .m_axi_gmem_pw_w_0_ARPROT(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARPROT),
    .m_axi_gmem_pw_w_0_ARQOS(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARQOS),
    .m_axi_gmem_pw_w_0_ARREGION(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARREGION),
    .m_axi_gmem_pw_w_0_ARUSER(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARUSER),
    .m_axi_gmem_pw_w_0_RVALID(m_axi_gmem_pw_w_0_RVALID),
    .m_axi_gmem_pw_w_0_RREADY(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_RREADY),
    .m_axi_gmem_pw_w_0_RDATA(m_axi_gmem_pw_w_0_RDATA),
    .m_axi_gmem_pw_w_0_RLAST(m_axi_gmem_pw_w_0_RLAST),
    .m_axi_gmem_pw_w_0_RID(m_axi_gmem_pw_w_0_RID),
    .m_axi_gmem_pw_w_0_RFIFONUM(m_axi_gmem_pw_w_0_RFIFONUM),
    .m_axi_gmem_pw_w_0_RUSER(m_axi_gmem_pw_w_0_RUSER),
    .m_axi_gmem_pw_w_0_RRESP(m_axi_gmem_pw_w_0_RRESP),
    .m_axi_gmem_pw_w_0_BVALID(1'b0),
    .m_axi_gmem_pw_w_0_BREADY(grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_BREADY),
    .m_axi_gmem_pw_w_0_BRESP(2'd0),
    .m_axi_gmem_pw_w_0_BID(1'd0),
    .m_axi_gmem_pw_w_0_BUSER(1'd0),
    .pw_weights(pw_weights_read_reg_377),
    .pw_bias(pw_bias_read_reg_372),
    .m_axi_gmem_out_0_AWVALID(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWVALID),
    .m_axi_gmem_out_0_AWREADY(m_axi_gmem_out_0_AWREADY),
    .m_axi_gmem_out_0_AWADDR(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWADDR),
    .m_axi_gmem_out_0_AWID(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWID),
    .m_axi_gmem_out_0_AWLEN(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWLEN),
    .m_axi_gmem_out_0_AWSIZE(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWSIZE),
    .m_axi_gmem_out_0_AWBURST(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWBURST),
    .m_axi_gmem_out_0_AWLOCK(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWLOCK),
    .m_axi_gmem_out_0_AWCACHE(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWCACHE),
    .m_axi_gmem_out_0_AWPROT(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWPROT),
    .m_axi_gmem_out_0_AWQOS(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWQOS),
    .m_axi_gmem_out_0_AWREGION(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWREGION),
    .m_axi_gmem_out_0_AWUSER(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWUSER),
    .m_axi_gmem_out_0_WVALID(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WVALID),
    .m_axi_gmem_out_0_WREADY(m_axi_gmem_out_0_WREADY),
    .m_axi_gmem_out_0_WDATA(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WDATA),
    .m_axi_gmem_out_0_WSTRB(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WSTRB),
    .m_axi_gmem_out_0_WLAST(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WLAST),
    .m_axi_gmem_out_0_WID(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WID),
    .m_axi_gmem_out_0_WUSER(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WUSER),
    .m_axi_gmem_out_0_ARVALID(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARVALID),
    .m_axi_gmem_out_0_ARREADY(1'b0),
    .m_axi_gmem_out_0_ARADDR(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARADDR),
    .m_axi_gmem_out_0_ARID(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARID),
    .m_axi_gmem_out_0_ARLEN(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARLEN),
    .m_axi_gmem_out_0_ARSIZE(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARSIZE),
    .m_axi_gmem_out_0_ARBURST(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARBURST),
    .m_axi_gmem_out_0_ARLOCK(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARLOCK),
    .m_axi_gmem_out_0_ARCACHE(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARCACHE),
    .m_axi_gmem_out_0_ARPROT(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARPROT),
    .m_axi_gmem_out_0_ARQOS(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARQOS),
    .m_axi_gmem_out_0_ARREGION(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARREGION),
    .m_axi_gmem_out_0_ARUSER(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_ARUSER),
    .m_axi_gmem_out_0_RVALID(1'b0),
    .m_axi_gmem_out_0_RREADY(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_RREADY),
    .m_axi_gmem_out_0_RDATA(8'd0),
    .m_axi_gmem_out_0_RLAST(1'b0),
    .m_axi_gmem_out_0_RID(1'd0),
    .m_axi_gmem_out_0_RFIFONUM(11'd0),
    .m_axi_gmem_out_0_RUSER(1'd0),
    .m_axi_gmem_out_0_RRESP(2'd0),
    .m_axi_gmem_out_0_BVALID(m_axi_gmem_out_0_BVALID),
    .m_axi_gmem_out_0_BREADY(grp_pw_row_stage_fu_228_m_axi_gmem_out_0_BREADY),
    .m_axi_gmem_out_0_BRESP(m_axi_gmem_out_0_BRESP),
    .m_axi_gmem_out_0_BID(m_axi_gmem_out_0_BID),
    .m_axi_gmem_out_0_BUSER(m_axi_gmem_out_0_BUSER),
    .output_r(output_read_reg_367),
    .h_start(p_read_2_reg_362),
    .height(height_read_reg_357),
    .width(width_read_reg_352),
    .c_in(c_in_read_reg_347),
    .c_out(c_out_read_reg_342),
    .pw_act_zp(pw_act_zp_read_reg_337),
    .pw_wgt_zp(pw_wgt_zp_read_reg_332),
    .pw_out_zp(pw_out_zp_read_reg_327),
    .pw_M_mantissa(pw_M_mantissa_read_reg_322),
    .pw_M_shift(pw_M_shift_read_reg_317),
    .pw_use_bias(pw_use_bias_read_reg_312)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pw_row_stage_fu_228_ap_start_reg <= 1'b0;
    end else begin
        if ((((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd1) & (1'b0 == ap_block_state1_ignore_call0) & (1'b1 == ap_CS_fsm_state1)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd0) & (1'b0 == ap_block_state1_ignore_call0) & (1'b1 == ap_CS_fsm_state1)))) begin
            grp_pw_row_stage_fu_228_ap_start_reg <= 1'b1;
        end else if ((grp_pw_row_stage_fu_228_ap_ready == 1'b1)) begin
            grp_pw_row_stage_fu_228_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        c_in_read_reg_347 <= c_in;
        c_out_read_reg_342 <= c_out;
        height_read_reg_357 <= height;
        output_read_reg_367 <= output_r;
        p_read_2_reg_362 <= p_read2;
        p_read_3_reg_382 <= p_read1;
        p_read_4_reg_386 <= p_read;
        pw_M_mantissa_read_reg_322 <= pw_M_mantissa;
        pw_M_shift_read_reg_317 <= pw_M_shift;
        pw_act_zp_read_reg_337 <= pw_act_zp;
        pw_bias_read_reg_372 <= pw_bias;
        pw_out_zp_read_reg_327 <= pw_out_zp;
        pw_use_bias_read_reg_312 <= pw_use_bias;
        pw_weights_read_reg_377 <= pw_weights;
        pw_wgt_zp_read_reg_332 <= pw_wgt_zp;
        width_read_reg_352 <= width;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_0_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_0_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_0_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_0_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_10_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_10_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_10_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_10_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_11_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_11_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_11_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_11_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_12_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_12_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_12_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_12_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_13_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_13_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_13_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_13_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_14_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_14_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_14_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_14_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_15_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_15_q0 = p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_15_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_15_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_1_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_1_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_1_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_1_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_2_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_2_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_2_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_2_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_3_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_3_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_3_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_3_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_4_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_4_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_4_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_4_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_5_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_5_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_5_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_5_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_6_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_6_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_6_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_6_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_7_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_7_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_7_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_7_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_8_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_8_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_8_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_8_q0 = 'bx;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        if ((p_read_3_reg_382 == 1'd1)) begin
            grp_pw_row_stage_fu_228_inter_buf_9_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_q0;
        end else if ((p_read_3_reg_382 == 1'd0)) begin
            grp_pw_row_stage_fu_228_inter_buf_9_q0 = mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_q0;
        end else begin
            grp_pw_row_stage_fu_228_inter_buf_9_q0 = 'bx;
        end
    end else begin
        grp_pw_row_stage_fu_228_inter_buf_9_q0 = 'bx;
    end
end

always @ (*) begin
    if ((((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        m_axi_gmem_out_0_AWVALID = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWVALID;
    end else begin
        m_axi_gmem_out_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        m_axi_gmem_out_0_BREADY = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_BREADY;
    end else begin
        m_axi_gmem_out_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        m_axi_gmem_out_0_WVALID = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WVALID;
    end else begin
        m_axi_gmem_out_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        m_axi_gmem_pw_w_0_ARVALID = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARVALID;
    end else begin
        m_axi_gmem_pw_w_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((p_read_4_read_fu_222_p2 == 1'd1) & (p_read_3_read_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        m_axi_gmem_pw_w_0_RREADY = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_RREADY;
    end else begin
        m_axi_gmem_pw_w_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_ce0 = grp_pw_row_stage_fu_228_inter_buf_9_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_ce0 = grp_pw_row_stage_fu_228_inter_buf_8_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_ce0 = grp_pw_row_stage_fu_228_inter_buf_7_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_ce0 = grp_pw_row_stage_fu_228_inter_buf_6_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_ce0 = grp_pw_row_stage_fu_228_inter_buf_5_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_ce0 = grp_pw_row_stage_fu_228_inter_buf_4_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_ce0 = grp_pw_row_stage_fu_228_inter_buf_3_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_ce0 = grp_pw_row_stage_fu_228_inter_buf_2_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_ce0 = grp_pw_row_stage_fu_228_inter_buf_1_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_ce0 = grp_pw_row_stage_fu_228_inter_buf_0_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_ce0 = grp_pw_row_stage_fu_228_inter_buf_8_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_ce0 = grp_pw_row_stage_fu_228_inter_buf_7_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_ce0 = grp_pw_row_stage_fu_228_inter_buf_6_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_ce0 = grp_pw_row_stage_fu_228_inter_buf_5_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_ce0 = grp_pw_row_stage_fu_228_inter_buf_4_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_ce0 = grp_pw_row_stage_fu_228_inter_buf_3_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_ce0 = grp_pw_row_stage_fu_228_inter_buf_2_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_ce0 = grp_pw_row_stage_fu_228_inter_buf_1_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_ce0 = grp_pw_row_stage_fu_228_inter_buf_0_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_ce0 = grp_pw_row_stage_fu_228_inter_buf_9_ce0;
    end else begin
        mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_ce0 = grp_pw_row_stage_fu_228_inter_buf_10_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_ce0 = grp_pw_row_stage_fu_228_inter_buf_11_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_ce0 = grp_pw_row_stage_fu_228_inter_buf_12_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_ce0 = grp_pw_row_stage_fu_228_inter_buf_13_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_ce0 = grp_pw_row_stage_fu_228_inter_buf_14_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_ce0 = grp_pw_row_stage_fu_228_inter_buf_15_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_ce0 = grp_pw_row_stage_fu_228_inter_buf_10_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_ce0 = grp_pw_row_stage_fu_228_inter_buf_11_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_ce0 = grp_pw_row_stage_fu_228_inter_buf_12_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_ce0 = grp_pw_row_stage_fu_228_inter_buf_13_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_ce0 = grp_pw_row_stage_fu_228_inter_buf_14_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_ce0 = grp_pw_row_stage_fu_228_inter_buf_15_ce0;
    end else begin
        p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = (((ap_predicate_op27_call_state2 == 1'b1) & (grp_pw_row_stage_fu_228_ap_done == 1'b0)) | ((ap_predicate_op25_call_state2 == 1'b1) & (grp_pw_row_stage_fu_228_ap_done == 1'b0)));
end

always @ (*) begin
    ap_predicate_op25_call_state2 = ((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd0));
end

always @ (*) begin
    ap_predicate_op27_call_state2 = ((p_read_4_reg_386 == 1'd1) & (p_read_3_reg_382 == 1'd1));
end

assign grp_pw_row_stage_fu_228_ap_start = grp_pw_row_stage_fu_228_ap_start_reg;

assign m_axi_gmem_out_0_ARADDR = 64'd0;

assign m_axi_gmem_out_0_ARBURST = 2'd0;

assign m_axi_gmem_out_0_ARCACHE = 4'd0;

assign m_axi_gmem_out_0_ARID = 1'd0;

assign m_axi_gmem_out_0_ARLEN = 32'd0;

assign m_axi_gmem_out_0_ARLOCK = 2'd0;

assign m_axi_gmem_out_0_ARPROT = 3'd0;

assign m_axi_gmem_out_0_ARQOS = 4'd0;

assign m_axi_gmem_out_0_ARREGION = 4'd0;

assign m_axi_gmem_out_0_ARSIZE = 3'd0;

assign m_axi_gmem_out_0_ARUSER = 1'd0;

assign m_axi_gmem_out_0_ARVALID = 1'b0;

assign m_axi_gmem_out_0_AWADDR = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWADDR;

assign m_axi_gmem_out_0_AWBURST = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWBURST;

assign m_axi_gmem_out_0_AWCACHE = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWCACHE;

assign m_axi_gmem_out_0_AWID = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWID;

assign m_axi_gmem_out_0_AWLEN = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWLEN;

assign m_axi_gmem_out_0_AWLOCK = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWLOCK;

assign m_axi_gmem_out_0_AWPROT = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWPROT;

assign m_axi_gmem_out_0_AWQOS = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWQOS;

assign m_axi_gmem_out_0_AWREGION = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWREGION;

assign m_axi_gmem_out_0_AWSIZE = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWSIZE;

assign m_axi_gmem_out_0_AWUSER = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_AWUSER;

assign m_axi_gmem_out_0_RREADY = 1'b0;

assign m_axi_gmem_out_0_WDATA = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WDATA;

assign m_axi_gmem_out_0_WID = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WID;

assign m_axi_gmem_out_0_WLAST = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WLAST;

assign m_axi_gmem_out_0_WSTRB = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WSTRB;

assign m_axi_gmem_out_0_WUSER = grp_pw_row_stage_fu_228_m_axi_gmem_out_0_WUSER;

assign m_axi_gmem_pw_w_0_ARADDR = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARADDR;

assign m_axi_gmem_pw_w_0_ARBURST = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARBURST;

assign m_axi_gmem_pw_w_0_ARCACHE = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARCACHE;

assign m_axi_gmem_pw_w_0_ARID = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARID;

assign m_axi_gmem_pw_w_0_ARLEN = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARLEN;

assign m_axi_gmem_pw_w_0_ARLOCK = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARLOCK;

assign m_axi_gmem_pw_w_0_ARPROT = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARPROT;

assign m_axi_gmem_pw_w_0_ARQOS = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARQOS;

assign m_axi_gmem_pw_w_0_ARREGION = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARREGION;

assign m_axi_gmem_pw_w_0_ARSIZE = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARSIZE;

assign m_axi_gmem_pw_w_0_ARUSER = grp_pw_row_stage_fu_228_m_axi_gmem_pw_w_0_ARUSER;

assign m_axi_gmem_pw_w_0_AWADDR = 64'd0;

assign m_axi_gmem_pw_w_0_AWBURST = 2'd0;

assign m_axi_gmem_pw_w_0_AWCACHE = 4'd0;

assign m_axi_gmem_pw_w_0_AWID = 1'd0;

assign m_axi_gmem_pw_w_0_AWLEN = 32'd0;

assign m_axi_gmem_pw_w_0_AWLOCK = 2'd0;

assign m_axi_gmem_pw_w_0_AWPROT = 3'd0;

assign m_axi_gmem_pw_w_0_AWQOS = 4'd0;

assign m_axi_gmem_pw_w_0_AWREGION = 4'd0;

assign m_axi_gmem_pw_w_0_AWSIZE = 3'd0;

assign m_axi_gmem_pw_w_0_AWUSER = 1'd0;

assign m_axi_gmem_pw_w_0_AWVALID = 1'b0;

assign m_axi_gmem_pw_w_0_BREADY = 1'b0;

assign m_axi_gmem_pw_w_0_WDATA = 32'd0;

assign m_axi_gmem_pw_w_0_WID = 1'd0;

assign m_axi_gmem_pw_w_0_WLAST = 1'b0;

assign m_axi_gmem_pw_w_0_WSTRB = 4'd0;

assign m_axi_gmem_pw_w_0_WUSER = 1'd0;

assign m_axi_gmem_pw_w_0_WVALID = 1'b0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_10_address0 = grp_pw_row_stage_fu_228_inter_buf_9_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_11_address0 = grp_pw_row_stage_fu_228_inter_buf_8_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_12_address0 = grp_pw_row_stage_fu_228_inter_buf_7_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_13_address0 = grp_pw_row_stage_fu_228_inter_buf_6_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_14_address0 = grp_pw_row_stage_fu_228_inter_buf_5_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_15_address0 = grp_pw_row_stage_fu_228_inter_buf_4_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_16_address0 = grp_pw_row_stage_fu_228_inter_buf_3_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_17_address0 = grp_pw_row_stage_fu_228_inter_buf_2_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_18_address0 = grp_pw_row_stage_fu_228_inter_buf_1_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_19_address0 = grp_pw_row_stage_fu_228_inter_buf_0_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_1_address0 = grp_pw_row_stage_fu_228_inter_buf_8_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_2_address0 = grp_pw_row_stage_fu_228_inter_buf_7_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_3_address0 = grp_pw_row_stage_fu_228_inter_buf_6_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_4_address0 = grp_pw_row_stage_fu_228_inter_buf_5_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_5_address0 = grp_pw_row_stage_fu_228_inter_buf_4_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_6_address0 = grp_pw_row_stage_fu_228_inter_buf_3_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_7_address0 = grp_pw_row_stage_fu_228_inter_buf_2_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_8_address0 = grp_pw_row_stage_fu_228_inter_buf_1_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_9_address0 = grp_pw_row_stage_fu_228_inter_buf_0_address0;

assign mobilenet_block_accel_unsigned_char_const_unsigned_char_const_int_const_un_address0 = grp_pw_row_stage_fu_228_inter_buf_9_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_10_address0 = grp_pw_row_stage_fu_228_inter_buf_10_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_11_address0 = grp_pw_row_stage_fu_228_inter_buf_11_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_12_address0 = grp_pw_row_stage_fu_228_inter_buf_12_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_13_address0 = grp_pw_row_stage_fu_228_inter_buf_13_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_14_address0 = grp_pw_row_stage_fu_228_inter_buf_14_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_ping_15_address0 = grp_pw_row_stage_fu_228_inter_buf_15_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_10_address0 = grp_pw_row_stage_fu_228_inter_buf_10_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_11_address0 = grp_pw_row_stage_fu_228_inter_buf_11_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_12_address0 = grp_pw_row_stage_fu_228_inter_buf_12_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_13_address0 = grp_pw_row_stage_fu_228_inter_buf_13_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_14_address0 = grp_pw_row_stage_fu_228_inter_buf_14_address0;

assign p_ZZ21mobilenet_block_accelPKhS0_PKiS0_S2_PhiiiiiiiiiiiiiiiiE10inter_pong_15_address0 = grp_pw_row_stage_fu_228_inter_buf_15_address0;

assign p_read_3_read_fu_216_p2 = p_read1;

assign p_read_4_read_fu_222_p2 = p_read;

endmodule //mobilenet_block_accel_dataflow_in_loop_TILE_LOOP_1_Block_if_end_aft_proc
