-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mobilenet_block_accel_dw_row_stage_Pipeline_DW_LOOP_W is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_in_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_in_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_in_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_in_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_in_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_in_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_in_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_in_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_in_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_in_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    window_11_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_10_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_9_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_8_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_7_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_6_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    width : IN STD_LOGIC_VECTOR (30 downto 0);
    inter_buf_15_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_15_ce0 : OUT STD_LOGIC;
    inter_buf_15_we0 : OUT STD_LOGIC;
    inter_buf_15_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_14_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_14_ce0 : OUT STD_LOGIC;
    inter_buf_14_we0 : OUT STD_LOGIC;
    inter_buf_14_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_13_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_13_ce0 : OUT STD_LOGIC;
    inter_buf_13_we0 : OUT STD_LOGIC;
    inter_buf_13_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_12_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_12_ce0 : OUT STD_LOGIC;
    inter_buf_12_we0 : OUT STD_LOGIC;
    inter_buf_12_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_11_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_11_ce0 : OUT STD_LOGIC;
    inter_buf_11_we0 : OUT STD_LOGIC;
    inter_buf_11_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_10_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_10_ce0 : OUT STD_LOGIC;
    inter_buf_10_we0 : OUT STD_LOGIC;
    inter_buf_10_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_9_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_9_ce0 : OUT STD_LOGIC;
    inter_buf_9_we0 : OUT STD_LOGIC;
    inter_buf_9_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_8_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_8_ce0 : OUT STD_LOGIC;
    inter_buf_8_we0 : OUT STD_LOGIC;
    inter_buf_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_7_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_7_ce0 : OUT STD_LOGIC;
    inter_buf_7_we0 : OUT STD_LOGIC;
    inter_buf_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_6_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_6_ce0 : OUT STD_LOGIC;
    inter_buf_6_we0 : OUT STD_LOGIC;
    inter_buf_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_5_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_5_ce0 : OUT STD_LOGIC;
    inter_buf_5_we0 : OUT STD_LOGIC;
    inter_buf_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_4_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_4_ce0 : OUT STD_LOGIC;
    inter_buf_4_we0 : OUT STD_LOGIC;
    inter_buf_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_3_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_3_ce0 : OUT STD_LOGIC;
    inter_buf_3_we0 : OUT STD_LOGIC;
    inter_buf_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_2_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_2_ce0 : OUT STD_LOGIC;
    inter_buf_2_we0 : OUT STD_LOGIC;
    inter_buf_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_1_ce0 : OUT STD_LOGIC;
    inter_buf_1_we0 : OUT STD_LOGIC;
    inter_buf_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inter_buf_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    inter_buf_0_ce0 : OUT STD_LOGIC;
    inter_buf_0_we0 : OUT STD_LOGIC;
    inter_buf_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    line_buf_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    line_buf_2_ce0 : OUT STD_LOGIC;
    line_buf_2_we0 : OUT STD_LOGIC;
    line_buf_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    line_buf_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    line_buf_2_ce1 : OUT STD_LOGIC;
    line_buf_2_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    line_buf_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    line_buf_1_ce0 : OUT STD_LOGIC;
    line_buf_1_we0 : OUT STD_LOGIC;
    line_buf_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    line_buf_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    line_buf_1_ce1 : OUT STD_LOGIC;
    line_buf_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    line_buf_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    line_buf_ce0 : OUT STD_LOGIC;
    line_buf_we0 : OUT STD_LOGIC;
    line_buf_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    line_buf_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    mul102_cast : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln181_1 : IN STD_LOGIC_VECTOR (30 downto 0);
    zext_ln181 : IN STD_LOGIC_VECTOR (30 downto 0);
    input_r : IN STD_LOGIC_VECTOR (63 downto 0);
    dw_in_zp : IN STD_LOGIC_VECTOR (31 downto 0);
    b_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    b : IN STD_LOGIC_VECTOR (31 downto 0);
    b_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_val : IN STD_LOGIC_VECTOR (31 downto 0);
    dw_multiplier : IN STD_LOGIC_VECTOR (31 downto 0);
    half : IN STD_LOGIC_VECTOR (31 downto 0);
    dw_shift : IN STD_LOGIC_VECTOR (31 downto 0);
    dw_out_zp : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_58 : IN STD_LOGIC_VECTOR (16 downto 0);
    empty : IN STD_LOGIC_VECTOR (16 downto 0);
    dw_apply_relu6 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    p_out1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out1_ap_vld : OUT STD_LOGIC;
    p_out2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out2_ap_vld : OUT STD_LOGIC;
    p_out3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out3_ap_vld : OUT STD_LOGIC;
    p_out4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out4_ap_vld : OUT STD_LOGIC;
    p_out5 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out5_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mobilenet_block_accel_dw_row_stage_Pipeline_DW_LOOP_W is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln244_reg_1424 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln244_reg_1424_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal icmp_ln244_fu_844_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_in_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem_in_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal tobool_fu_789_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_reg_1414 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_reg_1419 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln244_reg_1424_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln244_reg_1424_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln244_reg_1424_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln244_reg_1424_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln244_reg_1424_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln244_reg_1424_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln244_reg_1424_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln244_reg_1424_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln244_reg_1424_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_in_addr_reg_1428 : STD_LOGIC_VECTOR (63 downto 0);
    signal line_buf_addr_reg_1434 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_1_addr_reg_1439 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445_pp0_iter2_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445_pp0_iter3_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445_pp0_iter4_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445_pp0_iter5_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445_pp0_iter6_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445_pp0_iter7_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445_pp0_iter8_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_2_addr_reg_1445_pp0_iter9_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal lb1_reg_1451 : STD_LOGIC_VECTOR (7 downto 0);
    signal lb1_reg_1451_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb1_reg_1451_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb1_reg_1451_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb1_reg_1451_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb1_reg_1451_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb1_reg_1451_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb1_reg_1451_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb1_reg_1451_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb0_reg_1457 : STD_LOGIC_VECTOR (7 downto 0);
    signal lb0_reg_1457_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb0_reg_1457_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb0_reg_1457_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb0_reg_1457_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb0_reg_1457_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb0_reg_1457_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lb0_reg_1457_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal in_val_reg_1463 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_load34_reg_1470 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_load33_reg_1475 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_load_reg_1480 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln282_8_fu_1053_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln282_8_reg_1485 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_q_fu_1103_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_q_reg_1490 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter10_stage0 : STD_LOGIC;
    signal zext_ln244_fu_856_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln292_fu_1223_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal add_ln248_2_fu_884_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal phi_mul_fu_216 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal add_ln292_1_fu_1199_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal empty_61_fu_220 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal empty_62_fu_224 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_63_fu_228 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal w_fu_232 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln244_fu_850_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_sig_allocacmp_w_2 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_64_fu_236 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_65_fu_240 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_66_fu_244 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal line_buf_1_ce1_local : STD_LOGIC;
    signal line_buf_1_we0_local : STD_LOGIC;
    signal line_buf_1_ce0_local : STD_LOGIC;
    signal line_buf_2_ce1_local : STD_LOGIC;
    signal line_buf_2_we0_local : STD_LOGIC;
    signal line_buf_2_ce0_local : STD_LOGIC;
    signal line_buf_ce0_local : STD_LOGIC;
    signal line_buf_we0_local : STD_LOGIC;
    signal inter_buf_14_we0_local : STD_LOGIC;
    signal trunc_ln292_fu_1209_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln90_fu_1175_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal inter_buf_14_ce0_local : STD_LOGIC;
    signal inter_buf_13_we0_local : STD_LOGIC;
    signal inter_buf_13_ce0_local : STD_LOGIC;
    signal inter_buf_12_we0_local : STD_LOGIC;
    signal inter_buf_12_ce0_local : STD_LOGIC;
    signal inter_buf_11_we0_local : STD_LOGIC;
    signal inter_buf_11_ce0_local : STD_LOGIC;
    signal inter_buf_10_we0_local : STD_LOGIC;
    signal inter_buf_10_ce0_local : STD_LOGIC;
    signal inter_buf_9_we0_local : STD_LOGIC;
    signal inter_buf_9_ce0_local : STD_LOGIC;
    signal inter_buf_8_we0_local : STD_LOGIC;
    signal inter_buf_8_ce0_local : STD_LOGIC;
    signal inter_buf_7_we0_local : STD_LOGIC;
    signal inter_buf_7_ce0_local : STD_LOGIC;
    signal inter_buf_6_we0_local : STD_LOGIC;
    signal inter_buf_6_ce0_local : STD_LOGIC;
    signal inter_buf_5_we0_local : STD_LOGIC;
    signal inter_buf_5_ce0_local : STD_LOGIC;
    signal inter_buf_4_we0_local : STD_LOGIC;
    signal inter_buf_4_ce0_local : STD_LOGIC;
    signal inter_buf_3_we0_local : STD_LOGIC;
    signal inter_buf_3_ce0_local : STD_LOGIC;
    signal inter_buf_2_we0_local : STD_LOGIC;
    signal inter_buf_2_ce0_local : STD_LOGIC;
    signal inter_buf_1_we0_local : STD_LOGIC;
    signal inter_buf_1_ce0_local : STD_LOGIC;
    signal inter_buf_0_we0_local : STD_LOGIC;
    signal inter_buf_0_ce0_local : STD_LOGIC;
    signal inter_buf_15_we0_local : STD_LOGIC;
    signal inter_buf_15_ce0_local : STD_LOGIC;
    signal mul_ln282_fu_732_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_1_fu_736_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_2_fu_740_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_3_fu_744_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_4_fu_748_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_5_fu_752_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_6_fu_756_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_7_fu_760_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_8_fu_764_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln248_fu_772_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul102_cast_cast_fu_785_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln244_1_fu_863_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln248_fu_867_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln181_cast_fu_776_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln248_1_fu_878_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln248_fu_772_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln275_fu_919_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln275_1_fu_929_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln275_2_fu_939_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln275_3_fu_948_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln275_4_fu_958_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln275_5_fu_968_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln275_6_fu_977_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln275_7_fu_987_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln275_8_fu_997_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_1_fu_736_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_fu_732_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_7_fu_760_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln282_1_fu_1011_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_2_fu_740_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln282_2_fu_1017_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln282_fu_1006_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_5_fu_752_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_3_fu_744_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_6_fu_756_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_4_fu_748_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln282_5_fu_1035_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_8_fu_764_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln282_6_fu_1041_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln282_4_fu_1029_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln282_7_fu_1047_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln282_3_fu_1023_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln282_9_fu_768_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln81_fu_1086_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ashr_ln81_fu_1091_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal scaled_fu_1096_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln287_fu_1111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_q_1_fu_1115_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_q_2_fu_1121_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_41_fu_1135_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_40_fu_1127_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln90_fu_1155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_fu_1145_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln90_fu_1169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln90_1_fu_1161_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln92_fu_1151_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln292_fu_1204_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal lshr_ln_fu_1213_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln248_fu_772_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mobilenet_block_accel_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_block_accel_mul_33s_31ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (32 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component mobilenet_block_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_1_1_U50 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln282_fu_732_p0,
        din1 => b_4,
        dout => mul_ln282_fu_732_p2);

    mul_32s_32s_32_1_1_U51 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln282_1_fu_736_p0,
        din1 => b_7,
        dout => mul_ln282_1_fu_736_p2);

    mul_32s_32s_32_1_1_U52 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln282_2_fu_740_p0,
        din1 => b_6,
        dout => mul_ln282_2_fu_740_p2);

    mul_32s_32s_32_1_1_U53 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln282_3_fu_744_p0,
        din1 => b,
        dout => mul_ln282_3_fu_744_p2);

    mul_32s_32s_32_1_1_U54 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln282_4_fu_748_p0,
        din1 => b_5,
        dout => mul_ln282_4_fu_748_p2);

    mul_32s_32s_32_1_1_U55 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln282_5_fu_752_p0,
        din1 => b_1,
        dout => mul_ln282_5_fu_752_p2);

    mul_32s_32s_32_1_1_U56 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln282_6_fu_756_p0,
        din1 => b_2,
        dout => mul_ln282_6_fu_756_p2);

    mul_32s_32s_32_1_1_U57 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln282_7_fu_760_p0,
        din1 => b_3,
        dout => mul_ln282_7_fu_760_p2);

    mul_32s_32s_32_1_1_U58 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln282_8_fu_764_p0,
        din1 => b_8,
        dout => mul_ln282_8_fu_764_p2);

    mul_32s_32s_32_1_1_U59 : component mobilenet_block_accel_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => add_ln282_8_reg_1485,
        din1 => dw_multiplier,
        dout => mul_ln282_9_fu_768_p2);

    mul_33s_31ns_64_1_1_U60 : component mobilenet_block_accel_mul_33s_31ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 33,
        din1_WIDTH => 31,
        dout_WIDTH => 64)
    port map (
        din0 => add_ln248_fu_867_p2,
        din1 => mul_ln248_fu_772_p1,
        dout => mul_ln248_fu_772_p2);

    flow_control_loop_pipe_sequential_init_U : component mobilenet_block_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter10_stage0)) then 
                    ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    empty_61_fu_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_61_fu_220 <= window_6_reload;
                elsif (((icmp_ln244_reg_1424_pp0_iter9_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
                    empty_61_fu_220 <= empty_64_fu_236;
                end if;
            end if; 
        end if;
    end process;

    empty_62_fu_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_62_fu_224 <= window_8_reload;
                elsif (((icmp_ln244_reg_1424_pp0_iter9_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
                    empty_62_fu_224 <= empty_65_fu_240;
                end if;
            end if; 
        end if;
    end process;

    empty_63_fu_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_63_fu_228 <= window_10_reload;
                elsif (((icmp_ln244_reg_1424_pp0_iter9_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
                    empty_63_fu_228 <= empty_66_fu_244;
                end if;
            end if; 
        end if;
    end process;

    empty_64_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_64_fu_236 <= window_7_reload;
                elsif (((icmp_ln244_reg_1424_pp0_iter9_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
                    empty_64_fu_236 <= lb0_reg_1457_pp0_iter9_reg;
                end if;
            end if; 
        end if;
    end process;

    empty_65_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_65_fu_240 <= window_9_reload;
                elsif (((icmp_ln244_reg_1424_pp0_iter9_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
                    empty_65_fu_240 <= lb1_reg_1451_pp0_iter9_reg;
                end if;
            end if; 
        end if;
    end process;

    empty_66_fu_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_66_fu_244 <= window_11_reload;
                elsif (((icmp_ln244_reg_1424_pp0_iter9_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
                    empty_66_fu_244 <= in_val_reg_1463;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_mul_fu_216 <= ap_const_lv17_0;
                elsif ((ap_enable_reg_pp0_iter12 = ap_const_logic_1)) then 
                    phi_mul_fu_216 <= add_ln292_1_fu_1199_p2;
                end if;
            end if; 
        end if;
    end process;

    w_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln244_fu_844_p2 = ap_const_lv1_0))) then 
                    w_fu_232 <= add_ln244_fu_850_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_232 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                add_ln282_8_reg_1485 <= add_ln282_8_fu_1053_p2;
                out_q_reg_1490 <= out_q_fu_1103_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln244_reg_1424_pp0_iter10_reg <= icmp_ln244_reg_1424_pp0_iter9_reg;
                icmp_ln244_reg_1424_pp0_iter2_reg <= icmp_ln244_reg_1424_pp0_iter1_reg;
                icmp_ln244_reg_1424_pp0_iter3_reg <= icmp_ln244_reg_1424_pp0_iter2_reg;
                icmp_ln244_reg_1424_pp0_iter4_reg <= icmp_ln244_reg_1424_pp0_iter3_reg;
                icmp_ln244_reg_1424_pp0_iter5_reg <= icmp_ln244_reg_1424_pp0_iter4_reg;
                icmp_ln244_reg_1424_pp0_iter6_reg <= icmp_ln244_reg_1424_pp0_iter5_reg;
                icmp_ln244_reg_1424_pp0_iter7_reg <= icmp_ln244_reg_1424_pp0_iter6_reg;
                icmp_ln244_reg_1424_pp0_iter8_reg <= icmp_ln244_reg_1424_pp0_iter7_reg;
                icmp_ln244_reg_1424_pp0_iter9_reg <= icmp_ln244_reg_1424_pp0_iter8_reg;
                in_val_reg_1463 <= m_axi_gmem_in_0_RDATA;
                lb0_reg_1457_pp0_iter3_reg <= lb0_reg_1457;
                lb0_reg_1457_pp0_iter4_reg <= lb0_reg_1457_pp0_iter3_reg;
                lb0_reg_1457_pp0_iter5_reg <= lb0_reg_1457_pp0_iter4_reg;
                lb0_reg_1457_pp0_iter6_reg <= lb0_reg_1457_pp0_iter5_reg;
                lb0_reg_1457_pp0_iter7_reg <= lb0_reg_1457_pp0_iter6_reg;
                lb0_reg_1457_pp0_iter8_reg <= lb0_reg_1457_pp0_iter7_reg;
                lb0_reg_1457_pp0_iter9_reg <= lb0_reg_1457_pp0_iter8_reg;
                lb1_reg_1451_pp0_iter2_reg <= lb1_reg_1451;
                lb1_reg_1451_pp0_iter3_reg <= lb1_reg_1451_pp0_iter2_reg;
                lb1_reg_1451_pp0_iter4_reg <= lb1_reg_1451_pp0_iter3_reg;
                lb1_reg_1451_pp0_iter5_reg <= lb1_reg_1451_pp0_iter4_reg;
                lb1_reg_1451_pp0_iter6_reg <= lb1_reg_1451_pp0_iter5_reg;
                lb1_reg_1451_pp0_iter7_reg <= lb1_reg_1451_pp0_iter6_reg;
                lb1_reg_1451_pp0_iter8_reg <= lb1_reg_1451_pp0_iter7_reg;
                lb1_reg_1451_pp0_iter9_reg <= lb1_reg_1451_pp0_iter8_reg;
                line_buf_2_addr_reg_1445_pp0_iter2_reg <= line_buf_2_addr_reg_1445_pp0_iter1_reg;
                line_buf_2_addr_reg_1445_pp0_iter3_reg <= line_buf_2_addr_reg_1445_pp0_iter2_reg;
                line_buf_2_addr_reg_1445_pp0_iter4_reg <= line_buf_2_addr_reg_1445_pp0_iter3_reg;
                line_buf_2_addr_reg_1445_pp0_iter5_reg <= line_buf_2_addr_reg_1445_pp0_iter4_reg;
                line_buf_2_addr_reg_1445_pp0_iter6_reg <= line_buf_2_addr_reg_1445_pp0_iter5_reg;
                line_buf_2_addr_reg_1445_pp0_iter7_reg <= line_buf_2_addr_reg_1445_pp0_iter6_reg;
                line_buf_2_addr_reg_1445_pp0_iter8_reg <= line_buf_2_addr_reg_1445_pp0_iter7_reg;
                line_buf_2_addr_reg_1445_pp0_iter9_reg <= line_buf_2_addr_reg_1445_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                gmem_in_addr_reg_1428 <= add_ln248_2_fu_884_p2;
                icmp_ln244_reg_1424 <= icmp_ln244_fu_844_p2;
                icmp_ln244_reg_1424_pp0_iter1_reg <= icmp_ln244_reg_1424;
                line_buf_1_addr_reg_1439 <= zext_ln244_fu_856_p1(7 - 1 downto 0);
                line_buf_2_addr_reg_1445 <= zext_ln244_fu_856_p1(7 - 1 downto 0);
                line_buf_2_addr_reg_1445_pp0_iter1_reg <= line_buf_2_addr_reg_1445;
                line_buf_addr_reg_1434 <= zext_ln244_fu_856_p1(7 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                cmp_i_reg_1419 <= cmp_i_fu_795_p2;
                tobool_reg_1414 <= tobool_fu_789_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                lb0_reg_1457 <= line_buf_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                lb1_reg_1451 <= line_buf_1_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                p_load33_reg_1475 <= empty_65_fu_240;
                p_load34_reg_1470 <= empty_64_fu_236;
                p_load_reg_1480 <= empty_66_fu_244;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln244_fu_850_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_w_2) + unsigned(ap_const_lv31_1));
    add_ln248_1_fu_878_p2 <= std_logic_vector(unsigned(zext_ln181_cast_fu_776_p1) + unsigned(input_r));
    add_ln248_2_fu_884_p2 <= std_logic_vector(unsigned(add_ln248_1_fu_878_p2) + unsigned(mul_ln248_fu_772_p2));
    add_ln248_fu_867_p2 <= std_logic_vector(signed(mul102_cast_cast_fu_785_p1) + signed(zext_ln244_1_fu_863_p1));
    add_ln282_1_fu_1011_p2 <= std_logic_vector(unsigned(mul_ln282_fu_732_p2) + unsigned(mul_ln282_7_fu_760_p2));
    add_ln282_2_fu_1017_p2 <= std_logic_vector(unsigned(add_ln282_1_fu_1011_p2) + unsigned(mul_ln282_2_fu_740_p2));
    add_ln282_3_fu_1023_p2 <= std_logic_vector(unsigned(add_ln282_2_fu_1017_p2) + unsigned(add_ln282_fu_1006_p2));
    add_ln282_4_fu_1029_p2 <= std_logic_vector(unsigned(mul_ln282_5_fu_752_p2) + unsigned(mul_ln282_3_fu_744_p2));
    add_ln282_5_fu_1035_p2 <= std_logic_vector(unsigned(mul_ln282_6_fu_756_p2) + unsigned(mul_ln282_4_fu_748_p2));
    add_ln282_6_fu_1041_p2 <= std_logic_vector(unsigned(add_ln282_5_fu_1035_p2) + unsigned(mul_ln282_8_fu_764_p2));
    add_ln282_7_fu_1047_p2 <= std_logic_vector(unsigned(add_ln282_6_fu_1041_p2) + unsigned(add_ln282_4_fu_1029_p2));
    add_ln282_8_fu_1053_p2 <= std_logic_vector(unsigned(add_ln282_7_fu_1047_p2) + unsigned(add_ln282_3_fu_1023_p2));
    add_ln282_fu_1006_p2 <= std_logic_vector(unsigned(bias_val) + unsigned(mul_ln282_1_fu_736_p2));
    add_ln292_1_fu_1199_p2 <= std_logic_vector(unsigned(phi_mul_fu_216) + unsigned(empty_58));
    add_ln292_fu_1204_p2 <= std_logic_vector(unsigned(phi_mul_fu_216) + unsigned(empty));
    add_ln81_fu_1086_p2 <= std_logic_vector(unsigned(mul_ln282_9_fu_768_p2) + unsigned(half));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_block_state2_io_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_io_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_block_state2_io_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_io_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(m_axi_gmem_in_0_RVALID, icmp_ln244_reg_1424_pp0_iter8_reg)
    begin
                ap_block_state10_pp0_stage0_iter9 <= ((icmp_ln244_reg_1424_pp0_iter8_reg = ap_const_lv1_0) and (m_axi_gmem_in_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_state2_io_grp1_assign_proc : process(m_axi_gmem_in_0_ARREADY, icmp_ln244_reg_1424)
    begin
                ap_block_state2_io_grp1 <= ((m_axi_gmem_in_0_ARREADY = ap_const_logic_0) and (icmp_ln244_reg_1424 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln244_fu_844_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln244_fu_844_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter10_stage0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_subdone, icmp_ln244_reg_1424_pp0_iter9_reg)
    begin
        if (((icmp_ln244_reg_1424_pp0_iter9_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter10_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter10_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter11_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_w_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, w_fu_232)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_w_2 <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_w_2 <= w_fu_232;
        end if; 
    end process;

    ashr_ln81_fu_1091_p2 <= std_logic_vector(shift_right(signed(add_ln81_fu_1086_p2),to_integer(unsigned('0' & dw_shift(31-1 downto 0)))));
    cmp_i_fu_795_p2 <= "1" when (signed(dw_shift) < signed(ap_const_lv32_1)) else "0";

    gmem_in_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_in_0_ARREADY, icmp_ln244_reg_1424, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (icmp_ln244_reg_1424 = ap_const_lv1_0))) then 
            gmem_in_blk_n_AR <= m_axi_gmem_in_0_ARREADY;
        else 
            gmem_in_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_in_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem_in_0_RVALID, icmp_ln244_reg_1424_pp0_iter8_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (icmp_ln244_reg_1424_pp0_iter8_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem_in_blk_n_R <= m_axi_gmem_in_0_RVALID;
        else 
            gmem_in_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln244_fu_844_p2 <= "1" when (ap_sig_allocacmp_w_2 = width) else "0";
    icmp_ln287_fu_1111_p2 <= "1" when (signed(out_q_reg_1490) < signed(dw_out_zp)) else "0";
    icmp_ln91_fu_1145_p2 <= "1" when (signed(tmp_41_fu_1135_p4) > signed(ap_const_lv24_0)) else "0";
    inter_buf_0_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_0_ce0 <= inter_buf_0_ce0_local;

    inter_buf_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_0_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_0_d0 <= select_ln90_fu_1175_p3;
    inter_buf_0_we0 <= inter_buf_0_we0_local;

    inter_buf_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_0_we0_local <= ap_const_logic_1;
        else 
            inter_buf_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_10_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_10_ce0 <= inter_buf_10_ce0_local;

    inter_buf_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_10_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_10_d0 <= select_ln90_fu_1175_p3;
    inter_buf_10_we0 <= inter_buf_10_we0_local;

    inter_buf_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_A) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_10_we0_local <= ap_const_logic_1;
        else 
            inter_buf_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_11_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_11_ce0 <= inter_buf_11_ce0_local;

    inter_buf_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_11_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_11_d0 <= select_ln90_fu_1175_p3;
    inter_buf_11_we0 <= inter_buf_11_we0_local;

    inter_buf_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_B) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_11_we0_local <= ap_const_logic_1;
        else 
            inter_buf_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_12_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_12_ce0 <= inter_buf_12_ce0_local;

    inter_buf_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_12_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_12_d0 <= select_ln90_fu_1175_p3;
    inter_buf_12_we0 <= inter_buf_12_we0_local;

    inter_buf_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_C) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_12_we0_local <= ap_const_logic_1;
        else 
            inter_buf_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_13_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_13_ce0 <= inter_buf_13_ce0_local;

    inter_buf_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_13_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_13_d0 <= select_ln90_fu_1175_p3;
    inter_buf_13_we0 <= inter_buf_13_we0_local;

    inter_buf_13_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_D) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_13_we0_local <= ap_const_logic_1;
        else 
            inter_buf_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_14_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_14_ce0 <= inter_buf_14_ce0_local;

    inter_buf_14_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_14_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_14_d0 <= select_ln90_fu_1175_p3;
    inter_buf_14_we0 <= inter_buf_14_we0_local;

    inter_buf_14_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_E) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_14_we0_local <= ap_const_logic_1;
        else 
            inter_buf_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_15_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_15_ce0 <= inter_buf_15_ce0_local;

    inter_buf_15_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_15_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_15_d0 <= select_ln90_fu_1175_p3;
    inter_buf_15_we0 <= inter_buf_15_we0_local;

    inter_buf_15_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_F) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_15_we0_local <= ap_const_logic_1;
        else 
            inter_buf_15_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_1_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_1_ce0 <= inter_buf_1_ce0_local;

    inter_buf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_1_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_1_d0 <= select_ln90_fu_1175_p3;
    inter_buf_1_we0 <= inter_buf_1_we0_local;

    inter_buf_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_1) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_1_we0_local <= ap_const_logic_1;
        else 
            inter_buf_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_2_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_2_ce0 <= inter_buf_2_ce0_local;

    inter_buf_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_2_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_2_d0 <= select_ln90_fu_1175_p3;
    inter_buf_2_we0 <= inter_buf_2_we0_local;

    inter_buf_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_2) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_2_we0_local <= ap_const_logic_1;
        else 
            inter_buf_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_3_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_3_ce0 <= inter_buf_3_ce0_local;

    inter_buf_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_3_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_3_d0 <= select_ln90_fu_1175_p3;
    inter_buf_3_we0 <= inter_buf_3_we0_local;

    inter_buf_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_3) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_3_we0_local <= ap_const_logic_1;
        else 
            inter_buf_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_4_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_4_ce0 <= inter_buf_4_ce0_local;

    inter_buf_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_4_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_4_d0 <= select_ln90_fu_1175_p3;
    inter_buf_4_we0 <= inter_buf_4_we0_local;

    inter_buf_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_4) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_4_we0_local <= ap_const_logic_1;
        else 
            inter_buf_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_5_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_5_ce0 <= inter_buf_5_ce0_local;

    inter_buf_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_5_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_5_d0 <= select_ln90_fu_1175_p3;
    inter_buf_5_we0 <= inter_buf_5_we0_local;

    inter_buf_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_5) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_5_we0_local <= ap_const_logic_1;
        else 
            inter_buf_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_6_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_6_ce0 <= inter_buf_6_ce0_local;

    inter_buf_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_6_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_6_d0 <= select_ln90_fu_1175_p3;
    inter_buf_6_we0 <= inter_buf_6_we0_local;

    inter_buf_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_6) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_6_we0_local <= ap_const_logic_1;
        else 
            inter_buf_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_7_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_7_ce0 <= inter_buf_7_ce0_local;

    inter_buf_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_7_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_7_d0 <= select_ln90_fu_1175_p3;
    inter_buf_7_we0 <= inter_buf_7_we0_local;

    inter_buf_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_7) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_7_we0_local <= ap_const_logic_1;
        else 
            inter_buf_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_8_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_8_ce0 <= inter_buf_8_ce0_local;

    inter_buf_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_8_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_8_d0 <= select_ln90_fu_1175_p3;
    inter_buf_8_we0 <= inter_buf_8_we0_local;

    inter_buf_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_8) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_8_we0_local <= ap_const_logic_1;
        else 
            inter_buf_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_9_address0 <= zext_ln292_fu_1223_p1(13 - 1 downto 0);
    inter_buf_9_ce0 <= inter_buf_9_ce0_local;

    inter_buf_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_9_ce0_local <= ap_const_logic_1;
        else 
            inter_buf_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    inter_buf_9_d0 <= select_ln90_fu_1175_p3;
    inter_buf_9_we0 <= inter_buf_9_we0_local;

    inter_buf_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln292_fu_1209_p1)
    begin
        if (((trunc_ln292_fu_1209_p1 = ap_const_lv4_9) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            inter_buf_9_we0_local <= ap_const_logic_1;
        else 
            inter_buf_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_1_address0 <= line_buf_1_addr_reg_1439;
    line_buf_1_address1 <= zext_ln244_fu_856_p1(7 - 1 downto 0);
    line_buf_1_ce0 <= line_buf_1_ce0_local;

    line_buf_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            line_buf_1_ce0_local <= ap_const_logic_1;
        else 
            line_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_1_ce1 <= line_buf_1_ce1_local;

    line_buf_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            line_buf_1_ce1_local <= ap_const_logic_1;
        else 
            line_buf_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_1_d0 <= line_buf_2_q1;
    line_buf_1_we0 <= line_buf_1_we0_local;

    line_buf_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln244_reg_1424, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln244_reg_1424 = ap_const_lv1_0))) then 
            line_buf_1_we0_local <= ap_const_logic_1;
        else 
            line_buf_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_2_address0 <= line_buf_2_addr_reg_1445_pp0_iter9_reg;
    line_buf_2_address1 <= zext_ln244_fu_856_p1(7 - 1 downto 0);
    line_buf_2_ce0 <= line_buf_2_ce0_local;

    line_buf_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            line_buf_2_ce0_local <= ap_const_logic_1;
        else 
            line_buf_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_2_ce1 <= line_buf_2_ce1_local;

    line_buf_2_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            line_buf_2_ce1_local <= ap_const_logic_1;
        else 
            line_buf_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_2_d0 <= in_val_reg_1463;
    line_buf_2_we0 <= line_buf_2_we0_local;

    line_buf_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, icmp_ln244_reg_1424_pp0_iter9_reg)
    begin
        if (((icmp_ln244_reg_1424_pp0_iter9_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            line_buf_2_we0_local <= ap_const_logic_1;
        else 
            line_buf_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_address0 <= line_buf_addr_reg_1434;
    line_buf_ce0 <= line_buf_ce0_local;

    line_buf_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln244_reg_1424, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln244_reg_1424 = ap_const_lv1_0))) then 
            line_buf_ce0_local <= ap_const_logic_1;
        else 
            line_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_d0 <= line_buf_1_q1;
    line_buf_we0 <= line_buf_we0_local;

    line_buf_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln244_reg_1424, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln244_reg_1424 = ap_const_lv1_0))) then 
            line_buf_we0_local <= ap_const_logic_1;
        else 
            line_buf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln_fu_1213_p4 <= add_ln292_fu_1204_p2(16 downto 4);
    m_axi_gmem_in_0_ARADDR <= gmem_in_addr_reg_1428;
    m_axi_gmem_in_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_in_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_in_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_in_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem_in_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_in_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_in_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_in_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_in_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_in_0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_in_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln244_reg_1424, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (icmp_ln244_reg_1424 = ap_const_lv1_0))) then 
            m_axi_gmem_in_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_in_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_in_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_in_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_in_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_in_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_in_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_in_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_in_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_in_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_in_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_in_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_in_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter9, icmp_ln244_reg_1424_pp0_iter8_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (icmp_ln244_reg_1424_pp0_iter8_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_in_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_in_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_in_0_WDATA <= ap_const_lv8_0;
    m_axi_gmem_in_0_WID <= ap_const_lv1_0;
    m_axi_gmem_in_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_in_0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem_in_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_in_0_WVALID <= ap_const_logic_0;
        mul102_cast_cast_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul102_cast),33));

    mul_ln248_fu_772_p1 <= mul_ln248_fu_772_p10(31 - 1 downto 0);
    mul_ln248_fu_772_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln181_1),64));
    mul_ln282_1_fu_736_p0 <= std_logic_vector(unsigned(zext_ln275_7_fu_987_p1) - unsigned(dw_in_zp));
    mul_ln282_2_fu_740_p0 <= std_logic_vector(unsigned(zext_ln275_6_fu_977_p1) - unsigned(dw_in_zp));
    mul_ln282_3_fu_744_p0 <= std_logic_vector(unsigned(zext_ln275_fu_919_p1) - unsigned(dw_in_zp));
    mul_ln282_4_fu_748_p0 <= std_logic_vector(unsigned(zext_ln275_5_fu_968_p1) - unsigned(dw_in_zp));
    mul_ln282_5_fu_752_p0 <= std_logic_vector(unsigned(zext_ln275_1_fu_929_p1) - unsigned(dw_in_zp));
    mul_ln282_6_fu_756_p0 <= std_logic_vector(unsigned(zext_ln275_2_fu_939_p1) - unsigned(dw_in_zp));
    mul_ln282_7_fu_760_p0 <= std_logic_vector(unsigned(zext_ln275_3_fu_948_p1) - unsigned(dw_in_zp));
    mul_ln282_8_fu_764_p0 <= std_logic_vector(unsigned(zext_ln275_8_fu_997_p1) - unsigned(dw_in_zp));
    mul_ln282_fu_732_p0 <= std_logic_vector(unsigned(zext_ln275_4_fu_958_p1) - unsigned(dw_in_zp));
    or_ln90_fu_1169_p2 <= (tmp_40_fu_1127_p3 or icmp_ln91_fu_1145_p2);
    out_q_1_fu_1115_p3 <= 
        dw_out_zp when (icmp_ln287_fu_1111_p2(0) = '1') else 
        out_q_reg_1490;
    out_q_2_fu_1121_p3 <= 
        out_q_1_fu_1115_p3 when (tobool_reg_1414(0) = '1') else 
        out_q_reg_1490;
    out_q_fu_1103_p2 <= std_logic_vector(unsigned(scaled_fu_1096_p3) + unsigned(dw_out_zp));
    p_out <= p_load_reg_1480;
    p_out1 <= empty_63_fu_228;

    p_out1_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln244_reg_1424_pp0_iter10_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (icmp_ln244_reg_1424_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_out1_ap_vld <= ap_const_logic_1;
        else 
            p_out1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out2 <= p_load33_reg_1475;

    p_out2_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln244_reg_1424_pp0_iter10_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (icmp_ln244_reg_1424_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_out2_ap_vld <= ap_const_logic_1;
        else 
            p_out2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out3 <= empty_62_fu_224;

    p_out3_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln244_reg_1424_pp0_iter10_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (icmp_ln244_reg_1424_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_out3_ap_vld <= ap_const_logic_1;
        else 
            p_out3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out4 <= p_load34_reg_1470;

    p_out4_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln244_reg_1424_pp0_iter10_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (icmp_ln244_reg_1424_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_out4_ap_vld <= ap_const_logic_1;
        else 
            p_out4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out5 <= empty_61_fu_220;

    p_out5_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln244_reg_1424_pp0_iter10_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (icmp_ln244_reg_1424_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_out5_ap_vld <= ap_const_logic_1;
        else 
            p_out5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln244_reg_1424_pp0_iter10_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (icmp_ln244_reg_1424_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    scaled_fu_1096_p3 <= 
        mul_ln282_9_fu_768_p2 when (cmp_i_reg_1419(0) = '1') else 
        ashr_ln81_fu_1091_p2;
    select_ln90_1_fu_1161_p3 <= 
        ap_const_lv8_FF when (xor_ln90_fu_1155_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln90_fu_1175_p3 <= 
        select_ln90_1_fu_1161_p3 when (or_ln90_fu_1169_p2(0) = '1') else 
        trunc_ln92_fu_1151_p1;
    tmp_40_fu_1127_p3 <= out_q_2_fu_1121_p3(31 downto 31);
    tmp_41_fu_1135_p4 <= out_q_2_fu_1121_p3(31 downto 8);
    tobool_fu_789_p2 <= "0" when (dw_apply_relu6 = ap_const_lv32_0) else "1";
    trunc_ln292_fu_1209_p1 <= add_ln292_fu_1204_p2(4 - 1 downto 0);
    trunc_ln92_fu_1151_p1 <= out_q_2_fu_1121_p3(8 - 1 downto 0);
    xor_ln90_fu_1155_p2 <= (tmp_40_fu_1127_p3 xor ap_const_lv1_1);
    zext_ln181_cast_fu_776_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln181),64));
    zext_ln244_1_fu_863_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_w_2),33));
    zext_ln244_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_w_2),64));
    zext_ln275_1_fu_929_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_64_fu_236),32));
    zext_ln275_2_fu_939_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lb0_reg_1457_pp0_iter9_reg),32));
    zext_ln275_3_fu_948_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_62_fu_224),32));
    zext_ln275_4_fu_958_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_65_fu_240),32));
    zext_ln275_5_fu_968_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lb1_reg_1451_pp0_iter9_reg),32));
    zext_ln275_6_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_63_fu_228),32));
    zext_ln275_7_fu_987_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_66_fu_244),32));
    zext_ln275_8_fu_997_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_val_reg_1463),32));
    zext_ln275_fu_919_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_61_fu_220),32));
    zext_ln292_fu_1223_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_1213_p4),64));
end behav;
