// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenet_block_accel_dw_row_stage_Pipeline_DW_INIT_WIN (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        window_5,
        window_4,
        window_3,
        window_2,
        window_1,
        window,
        empty,
        window_11_out,
        window_11_out_ap_vld,
        window_10_out,
        window_10_out_ap_vld,
        window_9_out,
        window_9_out_ap_vld,
        window_8_out,
        window_8_out_ap_vld,
        window_7_out,
        window_7_out_ap_vld,
        window_6_out,
        window_6_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] window_5;
input  [7:0] window_4;
input  [7:0] window_3;
input  [7:0] window_2;
input  [7:0] window_1;
input  [7:0] window;
input  [7:0] empty;
output  [7:0] window_11_out;
output   window_11_out_ap_vld;
output  [7:0] window_10_out;
output   window_10_out_ap_vld;
output  [7:0] window_9_out;
output   window_9_out_ap_vld;
output  [7:0] window_8_out;
output   window_8_out_ap_vld;
output  [7:0] window_7_out;
output   window_7_out_ap_vld;
output  [7:0] window_6_out;
output   window_6_out_ap_vld;

reg ap_idle;
reg window_11_out_ap_vld;
reg window_10_out_ap_vld;
reg window_9_out_ap_vld;
reg window_8_out_ap_vld;
reg window_7_out_ap_vld;
reg window_6_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln229_fu_204_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [1:0] ky_fu_54;
wire   [1:0] add_ln229_fu_210_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [7:0] window_6_fu_58;
wire   [7:0] window_13_fu_287_p3;
reg   [7:0] window_7_fu_62;
wire   [7:0] window_14_fu_280_p3;
reg   [7:0] window_8_fu_66;
wire   [7:0] window_15_fu_273_p3;
reg   [7:0] window_9_fu_70;
wire   [7:0] window_16_fu_266_p3;
reg   [7:0] window_10_fu_74;
wire   [7:0] window_17_fu_259_p3;
reg   [7:0] window_11_fu_78;
wire   [7:0] window_12_fu_252_p3;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln232_fu_234_p2;
wire   [0:0] icmp_ln232_1_fu_240_p2;
wire   [0:0] or_ln232_fu_246_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ky_fu_54 = 2'd0;
#0 window_6_fu_58 = 8'd0;
#0 window_7_fu_62 = 8'd0;
#0 window_8_fu_66 = 8'd0;
#0 window_9_fu_70 = 8'd0;
#0 window_10_fu_74 = 8'd0;
#0 window_11_fu_78 = 8'd0;
#0 ap_done_reg = 1'b0;
end

mobilenet_block_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ky_fu_54 <= 2'd0;
        end else if (((icmp_ln229_fu_204_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ky_fu_54 <= add_ln229_fu_210_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            window_10_fu_74 <= window_4;
        end else if (((icmp_ln229_fu_204_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            window_10_fu_74 <= window_17_fu_259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            window_11_fu_78 <= window_5;
        end else if (((icmp_ln229_fu_204_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            window_11_fu_78 <= window_12_fu_252_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            window_6_fu_58 <= window;
        end else if (((icmp_ln229_fu_204_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            window_6_fu_58 <= window_13_fu_287_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            window_7_fu_62 <= window_1;
        end else if (((icmp_ln229_fu_204_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            window_7_fu_62 <= window_14_fu_280_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            window_8_fu_66 <= window_2;
        end else if (((icmp_ln229_fu_204_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            window_8_fu_66 <= window_15_fu_273_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            window_9_fu_70 <= window_3;
        end else if (((icmp_ln229_fu_204_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            window_9_fu_70 <= window_16_fu_266_p3;
        end
    end
end

always @ (*) begin
    if (((icmp_ln229_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln229_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        window_10_out_ap_vld = 1'b1;
    end else begin
        window_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln229_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        window_11_out_ap_vld = 1'b1;
    end else begin
        window_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln229_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        window_6_out_ap_vld = 1'b1;
    end else begin
        window_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln229_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        window_7_out_ap_vld = 1'b1;
    end else begin
        window_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln229_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        window_8_out_ap_vld = 1'b1;
    end else begin
        window_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln229_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        window_9_out_ap_vld = 1'b1;
    end else begin
        window_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln229_fu_210_p2 = (ky_fu_54 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln229_fu_204_p2 = ((ky_fu_54 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln232_1_fu_240_p2 = ((ky_fu_54 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln232_fu_234_p2 = ((ky_fu_54 == 2'd0) ? 1'b1 : 1'b0);

assign or_ln232_fu_246_p2 = (icmp_ln232_fu_234_p2 | icmp_ln232_1_fu_240_p2);

assign window_10_out = window_10_fu_74;

assign window_11_out = window_11_fu_78;

assign window_12_fu_252_p3 = ((or_ln232_fu_246_p2[0:0] == 1'b1) ? window_11_fu_78 : empty);

assign window_13_fu_287_p3 = ((icmp_ln232_fu_234_p2[0:0] == 1'b1) ? empty : window_6_fu_58);

assign window_14_fu_280_p3 = ((icmp_ln232_fu_234_p2[0:0] == 1'b1) ? empty : window_7_fu_62);

assign window_15_fu_273_p3 = ((icmp_ln232_1_fu_240_p2[0:0] == 1'b1) ? empty : window_8_fu_66);

assign window_16_fu_266_p3 = ((icmp_ln232_1_fu_240_p2[0:0] == 1'b1) ? empty : window_9_fu_70);

assign window_17_fu_259_p3 = ((or_ln232_fu_246_p2[0:0] == 1'b1) ? window_10_fu_74 : empty);

assign window_6_out = window_6_fu_58;

assign window_7_out = window_7_fu_62;

assign window_8_out = window_8_fu_66;

assign window_9_out = window_9_fu_70;

endmodule //mobilenet_block_accel_dw_row_stage_Pipeline_DW_INIT_WIN
