-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mobilenet_block_accel_dw_row_stage_Pipeline_DW_INIT_WIN is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    window_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    window_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    window_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    window_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    window_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    window : IN STD_LOGIC_VECTOR (7 downto 0);
    empty : IN STD_LOGIC_VECTOR (7 downto 0);
    window_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    window_11_out_ap_vld : OUT STD_LOGIC;
    window_10_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    window_10_out_ap_vld : OUT STD_LOGIC;
    window_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    window_9_out_ap_vld : OUT STD_LOGIC;
    window_8_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    window_8_out_ap_vld : OUT STD_LOGIC;
    window_7_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    window_7_out_ap_vld : OUT STD_LOGIC;
    window_6_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    window_6_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mobilenet_block_accel_dw_row_stage_Pipeline_DW_INIT_WIN is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln229_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ky_fu_54 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln229_fu_210_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal window_6_fu_58 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal window_13_fu_287_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_7_fu_62 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal window_14_fu_280_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_8_fu_66 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal window_15_fu_273_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_9_fu_70 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal window_16_fu_266_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_10_fu_74 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal window_17_fu_259_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_11_fu_78 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal window_12_fu_252_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln232_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln232_1_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln232_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mobilenet_block_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mobilenet_block_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ky_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ky_fu_54 <= ap_const_lv2_0;
                elsif (((icmp_ln229_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ky_fu_54 <= add_ln229_fu_210_p2;
                end if;
            end if; 
        end if;
    end process;

    window_10_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    window_10_fu_74 <= window_4;
                elsif (((icmp_ln229_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    window_10_fu_74 <= window_17_fu_259_p3;
                end if;
            end if; 
        end if;
    end process;

    window_11_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    window_11_fu_78 <= window_5;
                elsif (((icmp_ln229_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    window_11_fu_78 <= window_12_fu_252_p3;
                end if;
            end if; 
        end if;
    end process;

    window_6_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    window_6_fu_58 <= window;
                elsif (((icmp_ln229_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    window_6_fu_58 <= window_13_fu_287_p3;
                end if;
            end if; 
        end if;
    end process;

    window_7_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    window_7_fu_62 <= window_1;
                elsif (((icmp_ln229_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    window_7_fu_62 <= window_14_fu_280_p3;
                end if;
            end if; 
        end if;
    end process;

    window_8_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    window_8_fu_66 <= window_2;
                elsif (((icmp_ln229_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    window_8_fu_66 <= window_15_fu_273_p3;
                end if;
            end if; 
        end if;
    end process;

    window_9_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    window_9_fu_70 <= window_3;
                elsif (((icmp_ln229_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    window_9_fu_70 <= window_16_fu_266_p3;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln229_fu_210_p2 <= std_logic_vector(unsigned(ky_fu_54) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln229_fu_204_p2)
    begin
        if (((icmp_ln229_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln229_fu_204_p2 <= "1" when (ky_fu_54 = ap_const_lv2_3) else "0";
    icmp_ln232_1_fu_240_p2 <= "1" when (ky_fu_54 = ap_const_lv2_1) else "0";
    icmp_ln232_fu_234_p2 <= "1" when (ky_fu_54 = ap_const_lv2_0) else "0";
    or_ln232_fu_246_p2 <= (icmp_ln232_fu_234_p2 or icmp_ln232_1_fu_240_p2);
    window_10_out <= window_10_fu_74;

    window_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln229_fu_204_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln229_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            window_10_out_ap_vld <= ap_const_logic_1;
        else 
            window_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    window_11_out <= window_11_fu_78;

    window_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln229_fu_204_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln229_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            window_11_out_ap_vld <= ap_const_logic_1;
        else 
            window_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    window_12_fu_252_p3 <= 
        window_11_fu_78 when (or_ln232_fu_246_p2(0) = '1') else 
        empty;
    window_13_fu_287_p3 <= 
        empty when (icmp_ln232_fu_234_p2(0) = '1') else 
        window_6_fu_58;
    window_14_fu_280_p3 <= 
        empty when (icmp_ln232_fu_234_p2(0) = '1') else 
        window_7_fu_62;
    window_15_fu_273_p3 <= 
        empty when (icmp_ln232_1_fu_240_p2(0) = '1') else 
        window_8_fu_66;
    window_16_fu_266_p3 <= 
        empty when (icmp_ln232_1_fu_240_p2(0) = '1') else 
        window_9_fu_70;
    window_17_fu_259_p3 <= 
        window_10_fu_74 when (or_ln232_fu_246_p2(0) = '1') else 
        empty;
    window_6_out <= window_6_fu_58;

    window_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln229_fu_204_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln229_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            window_6_out_ap_vld <= ap_const_logic_1;
        else 
            window_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    window_7_out <= window_7_fu_62;

    window_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln229_fu_204_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln229_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            window_7_out_ap_vld <= ap_const_logic_1;
        else 
            window_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    window_8_out <= window_8_fu_66;

    window_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln229_fu_204_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln229_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            window_8_out_ap_vld <= ap_const_logic_1;
        else 
            window_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    window_9_out <= window_9_fu_70;

    window_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln229_fu_204_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln229_fu_204_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            window_9_out_ap_vld <= ap_const_logic_1;
        else 
            window_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
